### ISSUE TITLE
Difference !!!

### ISSUE THREAD

**Issue by DeChrish** [lukesampson/scoop#1000]
How is Scoop differ from https://chocolatey.org/ ???

**Comment by lukesampson** [comment]
There's a comparison [here](https://github.com/lukesampson/scoop/wiki/Chocolatey-Comparison). This was written almost 3 years ago, but I think it's still fairly accurate.

**Comment by DeChrish** [comment]
visual studio packages are included in scoop?

**Comment by lukesampson** [comment]
Not sure what you mean by visual studio packages. If you mean extensions, then no, sorry.

Scoop does minimal installation, it's mainly about getting .exes on your path for command line use. You can run `scoop install nuget` and have `nuget` ready to install packages without a fuss, instead of finding the website, downloading, running an installer etc.

**Comment by DeChrish** [comment]
@lukesampson Example : https://chocolatey.org/packages/VS2010.ShellIntegratedRedist

**Comment by lukesampson** [comment]
We don't have a installation package for VS2010 integrated shell. It should be possible to install using Scoop, it's just a matter of creating a scoop [manifest](https://github.com/lukesampson/scoop/wiki/Creating-an-app-manifest) for it.

We do have [VS code](https://github.com/lukesampson/scoop-extras/blob/master/vscode.json) and [Visual C++](https://github.com/lukesampson/scoop-extras/blob/master/visualc.json) in the extras bucket.
