### ISSUE TITLE
Error when attempting to use Scoop installed Python & PIP

### ISSUE THREAD

**Issue by brianjking** [lukesampson/scoop#1038]
```
Fatal error in launcher: Unable to create process using '"'
```

**Comment by lukesampson** [comment]
* Did you have Python already installed when you installed using scoop?
* Did you see any errors during the install?
* Are you using the vanilla Windows command shell, or something like cmder or console2?

**Comment by brianjking** [comment]
* Conemu, but the same error appears in Windows Command Shell (cmd.exe).
* Yes, I did have Python already installed. I've since uninstalled since it seems that Scoop should work much better than Chocolatey. 
* I don't recall seeing any errors during install, however, this was a few days ago when I first encountered this.

**Comment by lukesampson** [comment]
The python install is one of the few scoop packages that uses an .exe installer behind the scenes, because I don't think there is any simple/portable distribution we can use. So while scoop installs are usually self-contained, this is one case where it's not necessarily.

Uninstalling Python from the system could have affected things that the scoop install depends on. You might have to make sure it's uninstalled for the system (e.g. through the Windows Control Panel) and `scoop uninstall python`, and then try `scoop install python` again.

Also, are you running anything special to get this error? I've only really used it running e.g. `python3 myscript.py`.

**Comment by erikvullings** [comment]
On Windows 10, I first removed all previously installed versions of python from my system. Next, I ran `scoop install python` successfully. I needed to close my command console, but after reopening, I could use `pip` too e.g. `pip install markdown`. So from my end, this seems to be working well.

**Comment by rrelmy** [comment]
Me too

**Comment by snowman** [comment]
1. `$ scoop uninstall python`
2. delete scoop python persist directory `$ rmdir /S %USERPROFILE%\scoop\persist\python`
3. `$ scoop install python`

**Comment by joeygallegos** [comment]
I had this issue because I originally had Python installed by the MSI installer two years ago and then tried to use scoop to manage Python today. Uninstalling Python using the MSI installer/uninstaller left the PATH variable still in my environment, pointed to either the leftover pip.exe in Program Files folder or a folder with nothing inside of it. Removing these PATH variables **and** ensuring my scoop PATH variable was there helped resolve my issue. I can now run `python `and `pip `without issues.
