### ISSUE TITLE
Fails to specify "node.js" as dependency

### ISSUE THREAD

**Issue by martinlindhe** [lukesampson/scoop#1104]
While updating the yarn.json bucket, I noticed it lacked the node.js dependency. Node.js is defined in "bucket/node.js.json" so I tried using the "node.js" name and got the following error:

    couldn't find manifest for node.js

Using "nodejs" worked, but it's a bit confusing.

After using "nodejs" as dependency, installation dies because path got too long (Windows 7, x64);

```
...
failed to extract files from C:\Users\vm\AppData\Local\scoop\apps\nodejs\7.0.0\node-v7.0.0-x64.msi.
log file: ~\AppData\Local\scoop\apps\nodejs\7.0.0\msi.log
```

```
cat ~\AppData\Local\scoop\apps\nodejs\7.0.0\msi.log
=== Logging started: 2 nov  14:45:23 ===
Error 1320. The specified path is too long: C:\Users\vm\AppData\Local\scoop\apps\nodejs\7.0.0\_scoop_extract\nodejs\node_modules\npm\node_modules\npm-registry-client\node_modules\npmlog\node_modules\gauge\node_modules\string-width\node_modules\is-fullwidth-code-point\node_modules\number-is-nan
=== Logging stopped: 2 nov  14:45:34 ===
```

**Comment by lukesampson** [comment]
Yeah it's confusing, but the manifest for Node.js is just `nodejs.json` (see [here](https://github.com/lukesampson/scoop/blob/master/bucket/nodejs.json)), instead of `node.js.json`. I don't think any manifests use a dot

There was an update yesterday to address the long paths that node.js uses, but it involves reinstalling Scoop and all your programs. See my last comment for #847.

To reinstall, you would need to run something like `scoop list > ~/scoop_apps.txt; scoop uninstall scoop`, then `iex (new-object net.webclient).downloadstring('https://get.scoop.sh')` and manually re-install the apps you saved in `~/scoop_apps.txt`. You might lose some config and packages along the way too, such as npm packages.

**Comment by martinlindhe** [comment]
> Yeah it's confusing, but the manifest for Node.js is just nodejs.json (see here), instead of node.js.json. I don't think any manifests use a dot

Indeed. I must have misread, sorry about that.

**Comment by martinlindhe** [comment]
After uninstalling and reinstalling scoop, "scoop install nodejs" finally succeeded. Thanks for the help @lukesampson

**Comment by rivera15071976** [comment]
Please try using Long Path Tool
