### ISSUE TITLE
Updating apps is not documented

### ISSUE THREAD

**Issue by rrelmy** [lukesampson/scoop#1134]
There is no documentation regards updating apps, the only place where it is mentioned is the [header of the update script](https://github.com/lukesampson/scoop/blob/master/libexec/scoop-update.ps1).

The complete lifecycle of a app (install, update and uninstall) should be explained better.
For example in the readme or a separate FAQ page (like [brew](https://github.com/Homebrew/brew/blob/master/docs/FAQ.md))

I would even add a new command `scoop upgrade`

**Comment by lukesampson** [comment]
The headers are used by `scoop help` to print out the help info. E.g. `scoop help install` prints out the header you mentioned. The idea is that the code and the help documentation don't get out of sync.

I like the idea of an FAQ. I've started one [here](https://github.com/lukesampson/scoop/wiki/FAQ). If you're able to write some FAQs that'd be great. I think the wiki is public, so you should be able to edit it.

How do you see `scoop upgrade` working? The same as `scoop update *`? I find it confusing with Homebrew that there's an `update` and an `upgrade`. Since they're similar and I don't use it very often, I can't remember which one does which. For `update` and `uninstall`, Scoop has the convention that if you don't specify an app, you're talking about updating or uninstall Scoop itself.

**Comment by jwhipp** [comment]
I was about to open a suggestion on this one, at least, for an upgrade command..

The way I see where upgrade could work here is for scoop to parseat what it installed, compare to the current bucket versions, then update each as needed.   Much like apt-get upgrade or brew upgrade.

The update command already handles keeping scoop up2date and presumably, the package lists, so this would be a new added command to bulk update apps with no arguments.    

I can move to a new issue since this one is more or less about documentation vs. functionality.

**Comment by rasa** [comment]
This issue appears to have been resolved. If not, please reopen this ticket, or let us know. Thanks!
