### ISSUE TITLE
scoop is missing

### ISSUE THREAD

**Issue by rasikas** [lukesampson/scoop#118]
I have it installed for few days, but suddenly now it is not there.

```
PS C:\> scoop
scoop : The term 'scoop' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or
if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ scoop
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (scoop:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

when I try to install it again I'm getting the following message (hard to see as it crashes the powershell and exit, but able to get print screen)
![image](https://cloud.githubusercontent.com/assets/1381205/3253346/69d0a4ce-f1d5-11e3-83c8-2369f1f3803d.png)

```
 scoop is already installed and try to update
```

**Comment by tylerlong** [comment]
I meet the same issue. I solved it by deleting "C:\Users\[username]\appdata\local\scoop" then reinstall.

**Comment by Kyon0478** [comment]
It works after delete the folder in local PC.

**Comment by hairuo** [comment]
I met the same problem, and I find that the path is quite different in win7 as C:\Users\UserName\scoop\apps\scoop, not under \appdata\,  and the deep scoop folder(under \apps) is empty, so I delete the whole scoop under \UserName and use install it again, then it works. 

I guess the problem is due to the fall installation for the first time and so it's empty, but when using "scoop update", it can find the information of version and the directory, so it has some warnings like these"The term 'scoop' is not recognized as the name of a cmdlet..." but when try to install before deleting, it says "Scoop is already installed."

**Comment by butgit** [comment]
In my case, 'Path' in 'User variables for me' has been cleared, so I added to it ''C:\Users\<username>\scoop\shims" and now scoop is recognized.

**Comment by JARVIS-AI** [comment]
Yes adding shims to your PATH make it working again

Disappear for me after install **pshazz** prompt 
Better to check it
Something is wrong there
I can make a issue there in its page 
Just wanted to inform
