### ISSUE TITLE
Vagrant 1.9.1 cannot be installed

### ISSUE THREAD

**Issue by jeud** [lukesampson/scoop#1214]
Dear all

I used to be able to install vagrant 1.8.x successfully using `scoop install vagrant`

![](http://i.cubeupload.com/lVcAk2.png)

I tried  URL: <https://releases.hashicorp.com/vagrant/1.9.1/vagrant_1.9.1.msi> in the browser, the link is active as normal, so please guide

Thanks all

> I keep trying this installation for more than a week , I'm still not be able to complete it
>
> I also tried the installation using `PowerShell`, the result was the same

**Comment by lukesampson** [comment]
Thanks for reporting this problem. I think it was due to the Hashi Corp download server removing support for SSLv3 and TLS 1.0, and PowerShell / .NET not allowing newer TLS versions by default.

I've changed Scoop so that it will use whatever SSL/TLS protocols are available on your system. This fixes the problem for me. Can you please run `scoop update` and then test and confirm that it works for you too please?

**Comment by r15ch13** [comment]
checkver.ps1 should also get this fix, because it fails too.

**Comment by jeud** [comment]
@lukesampson thanks for this awesome tool :)

**Comment by jeud** [comment]
@lukesampson  thanks for this awesome tool :)

**Comment by lukesampson** [comment]
Thanks guys. @r15ch13: `checkver.ps1` should be fixed now too.
