### ISSUE TITLE
Change installation instructions to recommend RemoteSigned instead of Unrestricted

### ISSUE THREAD

**Issue by darthwalsh** [lukesampson/scoop#1221]
The installation instructions in the README and at http://scoop.sh/ recommend setting powershell executionpolicy to Unrestricted. Wouldn't RemoteSigned be a safer default? 

Many users probably don't understand the difference, and globally changing a user's scripting security defaults should probably have as little impact as possible.

On my machine I was able to install scoop and curl with RemoteSigned without a problem.

**Comment by lukesampson** [comment]
I thought `RemoteSigned` meant the scripts had to be signed? Some Scoop contributors looked into signing scripts a while ago, but we couldn't find a practical way to do this without compromising our ability to quickly and easily make changes and include outside contributions.

Let me know if I'm incorrect about how `RemoteSigned` works.

**Comment by wangzq** [comment]
When using `RemoteSigned` only remote scripts need to be signed, for the wrapper scripts or scripts from applications they are considered local they they don't need to be signed. As the bootstrap script of scoop, since you are using `iex` to invoke, the execution policy actually doesn't apply: see No. 4 in https://blog.netspi.com/15-ways-to-bypass-the-powershell-execution-policy/.

**Comment by lukesampson** [comment]
Yes `iex` is used to install Scoop, but what about subsequently running scoop.ps1?

**Comment by wangzq** [comment]
Set the execution policy to `RemoteSigned` will allow subsequently running scoop.ps1. I think the suggestion here is `RemoteSigned` is considered to be more safe than `Unrestricted`.

**Comment by lukesampson** [comment]
Okay thanks. I was sure I had tried `remotesigned` in the past and it didn't work, but it does seem okay. I will update the recommendation on the Scoop homepage.

**Comment by wangzq** [comment]
I remember the bootstrap setup script currently stops if the current execution policy is not set to `Unrestricted`, so it might also need to be updated. You may have to compare it using a range instead of just checking for one; in PowerShell it is defined as an enum:

	public enum ExecutionPolicy
	{
		Unrestricted,
		RemoteSigned,
		AllSigned,
		Restricted,
		Bypass,
		Undefined,
		Default = 3
	}

I personally would recommend just remove the check in the bootstrap script, in the documentation we should have already mentioned if the user is unable to run the bootstrap then they should run `Set-ExecutionPolicy RemoteSigned -s cu -force`.

**Comment by lukesampson** [comment]
Thanks for this. I've updated the install bootstrap script to check for `RemoteSigned` or lower security.

I've updated the docs, but I think it's good to have the check in the bootstrap as well—in case people don't read the docs first we can let them know how to proceed.

I've tested with a fresh user account with default settings and it appears to work well.

**Comment by darthwalsh** [comment]
Awesome, looks good! I found a little more documentation in the README that could be updated too

**Comment by tehbilly** [comment]
Commenting on old issue as I recently encountered this due to effective ExecutionPolicy being `Bypass`. The `-gt` check will return true for `Bypass`, however this is essentially `Unrestricted` minus even prompting.

Yes, I know `Bypass` is a terrible terrible evil, but there was an extenuating circumstance. :P
