### ISSUE TITLE
ImageMagick convert collides with windows 10 convert

### ISSUE THREAD

**Issue by zweimal** [lukesampson/scoop#1253]
ImageMagick convert collides with windows 10 convert.

First time after installation it works ok. Then, after reboot PS takes windows exe instead of ImageMagick's one.
It is very annoying.
Please help!

Thanks

**Comment by lukesampson** [comment]
I've added an `imconvert` alias to ImageMagick's `convert`, which should work even after rebooting. 

The ImageMagick install is a little confusing because it adds the app directory to the PATH environment variable (which allows convert.exe to work temporarily) but then shims all the executables anyway. Ideally I think it would just add the shims, but maybe there's a reason for doing it that way that I don't understand.

But I digress. To get the `imconvert` command you will need to force a reinstall of ImageMagick, so `scoop update; scoop uninstall imagemagick; scoop install imagemagick`.

**Comment by zweimal** [comment]
Thanks for the try, buddy.
Unfortunately it is not a real solution in case it is used by another application, such as in my case.
Rails uses ImageMagick's convert to process incoming images. I use it for test purpose so it is not so critical.

**Comment by lukesampson** [comment]
Let me know if you can figure out a way for ImageMagick's convert.exe to retain precedence after a reboot. It looks to me like Windows changes the order of your path environment variable on reboot to put `C:\Windows\System32` before `~/scoop/shims` and `~/scoop/apps/imagemagick/current`.

**Comment by deevus** [comment]
Try creating an alias in your $PROFILE file for it. Something like

`Set-Alias convert $(scoop which convert)`

When you start PowerShell that should get run.

**Comment by zweimal** [comment]
> Let me know if you can figure out a way for ImageMagick's convert.exe to retain precedence after a reboot. It looks to me like Windows changes the order of your path environment variable on reboot to put C:\Windows\System32 before ~/scoop/shims and ~/scoop/apps/imagemagick/current.

@lukesampson you made think and I was researching. After reading [this](https://technet.microsoft.com/en-us/library/cc723564.aspx#XSLTsection127121120120) article I got the conclusion I need to install it globally. I rebooted my computer and tada!! it worked 👍 

In brief:
`scoop install sudo` (In case you haven't got it already)
`sudo scoop install imagemagick -g`
Be happy 😃 

 @deevus I didn't try your suggestion but thanks anyway
