### ISSUE TITLE
Remove dependency of openjdk from ant and gradle

### ISSUE THREAD

**Issue by jinahya** [lukesampson/scoop#1263]
I'm worrying about this issue. It would be a debate.

Currently, `ant` and `gradle` has the `openjdk` as their dependency.
Well, it's not bad at all, but it's not more than convenience, either.

I believe almost all Java developers maintain specific JDKs(either oracle or open) in their system and don't want any unnecessary JDK being installed by just installing build tools such as `ant` or `gradle`.

I've already known about `scoop depends` and the `-i` switch with `scoop install/update` but it's not easy to consider every time I do things.

Please don't add `openjdk` as `maven`'s dependency even if I'm wrong.

**Comment by lukesampson** [comment]
Yes, this has caused problems and I'm tempted to just make `oraclejdk` the dependency and move it to the main bucket. Does anyone actually use `openjdk`?

**Comment by jinahya** [comment]
@lukesampson 
Replacing `openjdk` with `oraclejdk` is not my intention.
I'm suggesting to omit the dependency itself.
So that developers can install and manage their own flavored JDK independently.

**Comment by lukesampson** [comment]
Okay, omitting the dependency altogether would be fine by me too. What do other Java dev's think?

**Comment by tehbilly** [comment]
Thoroughly agree. As an aside, I wouldn't mind having the `-i` switch able to be turned on permanently.

**Comment by inosik** [comment]
What about saving the install options in `install.json` and reusing them when updating?

**Comment by Kisty** [comment]
Or perhaps detect if java is installed first, then say it's not installed and maybe prompt to download `openjdk`? I know the Android SDK uses a script to do this already `find_java32.exe`.

**Comment by deevus** [comment]
@Kisty How would you check if java is installed? 

I'm starting to feel like `scoop` is a little too eager to do things its way. For example I use `nvm` to install `nodejs` but if I then `scoop install yarn` it downloads the scoop version of nodejs, which I don't want. I can ignore dependencies using the `-i` flag but if a new update comes out it will try to install `nodejs` again. 

I think there's a few things around versioning that could be resolved

1. Installing a specific version of an app
2. Freezing an app 
3. Ignoring dependencies per app, or globally

# Problem 1

I worked on this a bit using git history commands. It works but it's not great because the scoop git history isn't perfect. Theres broken versions of apps and missing versions (with no way to add "new" old versions). 

A better idea I think is to leverage the scoop versions bucket. We have autoupdate functionality that I think could be tweaked a little bit to be able to generate specific version manifests. I can envisage users generating their own manifests for specific versions instead of needing to "put it in scoop". We could also build functionality so that they can contribute them easily.

# Problem 2

Simple solution: add a flag to `install.json` so that `scoop update *` doesn't pick it up. This may need some more thought. What do you think?

# Problem 3

To add to what everyone is saying here, this is a bit of a frustration with scoop right now. 

Ignoring dependencies can break some installations if the dependency isn't present at all on the system. However, the app should be smart enough to say "wheres my nodejs installation?", so it's probably a non-issue.

We have a global scope (via the `.scoop` dotfile), and an app scope (via `install.json`), so we can introduce  one flag (something like `ignore_dependencies`) that can be used in both scopes. A boolean value could be appropriate but we could also use a rules engine (i.e. with values like `true`, `false`, `"always"`, or an array of apps). Using a rules engine makes the dotfile more portable, but I'm not sure how many people would find that useful. 

I've probably got more to say but that's enough for now.

**Comment by deevus** [comment]
Just to add one more thing: I think when an app install has side-effects (installing dependencies for example), it should confirm with the user if they want to continue.

**Comment by Kisty** [comment]
@deevus The Android SDK has a find_java.bat script which looks on the path, registry and other locations to find java. https://android.googlesource.com/platform/sdk/+/refs/heads/master/find_java/src/source/find_java_exe.cpp
If you download the [Android SDK](https://dl.google.com/android/repository/tools_r25.2.3-windows.zip), in `tools/lib` you should find it.

**Comment by lukesampson** [comment]
@deevus,

Yes, dependencies seem to have become more of a hindrance than a help in most cases. Scoop manifests aren't as good at making dependency choices as users are. Dependency management is important for package managers, but Scoop isn't a package manager.

The idea about disabling dependencies globally or per-app would probably work. But isn't it patching over the underlying problem and making the more desirable situation, where users choose their own dependencies, optional?

This is something that can be solved pretty easily by removing dependencies from manifests where they aren't strictly necessary.

The idea about freezing an app sounds like it has potential. Same with allowing users to contribute versions more easily.

**Comment by Kisty** [comment]
@lukesampson Wait, so scoop _isn't_ a package manager, yet I thought it behaves like one?

**Comment by Kisty** [comment]
I see Scoop as apt-get but for Windows.

**Comment by lukesampson** [comment]
@Kisty it depends how you define package manager. I just mean that Scoop isn't a package manager in the same way that linux package managers like apt-get are, where programs are assembled with dependencies on many small pieces. Scoop is installing programs that are pre-packaged and much more self-contained.

**Comment by Kisty** [comment]
@lukesampson ah right! That means that the façade of it being a package manager like apt-get which compiles owes to the success of Scoop! You're doing it right, is what I mean! 😄

**Comment by lukesampson** [comment]
Manifests can now suggest apps that provide complementary features, rather than installing them automatically. I think this will be the recommended approach going forward, unless the dependency has no alternatives and is a small download (i.e. when we don't need to worry about other compatible choices and non-Scoop installs).

So we can use this for apps that previously automatically installed Java and Node.js.

E.g. here's a fresh install of Apache Ant when there's no JDK installed.

![capture](https://cloud.githubusercontent.com/assets/103446/22859932/da9a29c8-f141-11e6-9ccf-5fbcfdea3db3.PNG)

As you can see, it displays a message saying that "ant suggests installing extras/oraclejdk or openjdk", rather than going ahead and installing `openjdk` as it did in the past unless you remembered to use the `--independent` flag.
