### ISSUE TITLE
Feature request: scoop info <app>

### ISSUE THREAD

**Issue by mrkishi** [lukesampson/scoop#1291]
Something I always end up doing before installing an app is reading through its manifest file. I like to know if it's going to fill my path with shims, change the path itself or if it does something surprising during installation (looking at you, `nodejs`'s `rm .npmrc`).

What I'm proposing is that we add an `info <app>` command that reports just that: app version, added shims and warnings if it uses pre/post install scripts, changes the environment path or run standalone installers.

A possible unlisted command would be `manifest <app>` to either cat the manifest file in full or open it in the users' default editor.

Would this be a `yay` or a `nay`?

**Comment by lukesampson** [comment]
`info` would be great.

`manifest` could be a good power-user feature too. If it opens in an editor, we might just need to show a warning about how to make changes and submit them as patches, so that people don't go to the trouble of editing the file but then they can't submit it, and their `scoop update` breaks because their are uncommitted changes.

Are you happy to have a go at submitting a PR for `scoop info`?

**Comment by mrkishi** [comment]
Definitely, I'll work on it over the next few days. Thanks!

**Comment by CraftOz** [comment]
What do you think about "status <app_name>" instead of info? So without <app_name> you get at the moment a list if all apps and there status. It would be a logically drill-down for a more app-specific status.

**Comment by lukesampson** [comment]
@CodeFreezr that's a reasonable idea, but I think it might be confusing because `status` (without an `<app>` argument) only shows status for installed apps. I think `info` is a clearer and more distinct command name because we are aiming to show "information" about an app—most likely before it has been installed—rather than the app's "status".

**Comment by CodeFreezr** [comment]
Ok thats a point. The "info" Idea is to look before installing. Perhaps then it could makes sense to spend a short sentence about the purposes of the "shimes"?

**Comment by h404bi** [comment]
This issue could be closed.
