### ISSUE TITLE
Override cmdlets

### ISSUE THREAD

**Issue by cobarx** [lukesampson/scoop#1324]
When installing packages like coreutils that contain commands that are already provided by Powershell like mv, rm, etc., is there a way to force PS to use the Scoop versions?

The only way I've been able to find to do this would be using functions which is pretty clunky.

**Comment by deevus** [comment]
In your $PROFILE you can remove the aliases. Eg:

Remove-Item alias:/mv
Remove-Item alias:/rm

**Comment by cobarx** [comment]
This is great, thanks so much for the quick response. Having all these commands makes developing on Windows so much less painful.

I'm sure other people have had the same issue, it would nice to have this in the docs somewhere.

**Comment by mrgoodrich** [comment]
Since I would prefer Scoop versions of commands over PS, I attempted to `Remove-Item alias:/` all of the commands listed in https://github.com/lukesampson/scoop/blob/master/bucket/coreutils.json .  Some errored due to aliases not existing, but at the time of this reply the following list was successful, in case it will save some time for future readers.

Remove-Item alias:/mv
Remove-Item alias:/rm
Remove-Item alias:/cat
Remove-Item alias:/cp
Remove-Item alias:/echo
Remove-Item alias:/ls
Remove-Item alias:/ps
Remove-Item alias:/pwd
Remove-Item alias:/rmdir
