### ISSUE TITLE
Restart scoop services (OpenSSH)

### ISSUE THREAD

**Issue by Rudde** [lukesampson/scoop#1367]
Hello, how can I restart services installed with scoop? In my case, I've changed the ssh config file and would like to restart the service, but I can't find OpenSSH as service on my system, and find no way to restart it with scoop?

**Comment by lukesampson** [comment]
Scoop doesn't install OpenSSH as a windows service. It doesn't manage services at all.

I tried to write [a script to manage SSH in Powershell](https://github.com/lukesampson/pshazz/blob/master/plugins/ssh.ps1), but somewhere around Git version 2 or Windows version 10 it stopped working, and I haven't looked at it since.
