### ISSUE TITLE
No executables after updating to node.js 7.9.0 or re-installing

### ISSUE THREAD

**Issue by jeud** [lukesampson/scoop#1434]
Dear all

I just updated to the latest node.js 7.9.0, and also try to remove and re-install to the latest node.js 7.9.0

As I have discovered so far

1. There is no *node.exe* and *npm.exe* in *%UserProfile%\scoop\shimps* folder
2. The *%UserProfile%\scoop\apps\nodejs\bin* folder is empty

Please help
Thanks

**Comment by lukesampson** [comment]
1. The NodeJS install doesn't create shims (might be a while since you updated?). `node.exe` and `npm.cmd` should be inside `~/scoop/apps/nodejs/current/`. This directory is added to your path environment variable during the install, so `node` and `npm` commands should just work from the command line.
2. I think the bin folder is expected to be empty right after a fresh install. This is where globally installed npm packages will go, and they will be persisted across updates (this is a new feature since #1372).

**Comment by jeud** [comment]
@lukesampson I just realized that, sorry about reporting the issue,
finally **after** restarting my PC, node and npm executables are available at CLI call

thanks
