### ISSUE TITLE
Can't install scoop

### ISSUE THREAD

**Issue by andreiodi** [lukesampson/scoop#1464]
Exception calling "DownloadString" with "1" argument(s): "The operation has timed out"
At line:1 char:1
+ iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

Anyway to fix this issue ?

**Comment by lukesampson** [comment]
The download is timing out before PowerShell can load the install script. Maybe it was a temporary network issue. If you're behind a proxy, there are config instructions [here](https://github.com/lukesampson/scoop/wiki/Using-Scoop-behind-a-proxy).

**Comment by durhambell** [comment]
**Solution**: [Download the .ps1 here](https://raw.githubusercontent.com/lukesampson/scoop/master/bin/install.ps1), then run it manually.

**Explanation**: I know this is an old issue, but I also ran across the same behavior. One question for @andreiodi : what Windows version are/were you using? I encountered this error (also resulting from a timeout) on Windows Server 2016 D.C.E.. After a little digging I found some similar issues other people had with `net.webclient` (specifically on Win Server) disliking the fact that it was being passed to another address after validating the server certificate.

The script validates the cert at `https://get.scoop.sh`, but the actual install script is served from `https://raw.githubusercontent.com/lukesampson/scoop/master/bin/install.ps1`. I was able to circumvent the hiccup by simply executing the `install.ps1` manually instead of trying to have the (very elegant) `Invoke-Expression` command do it all for me.

Curiously, the issue still persisted after changing the execution policy, which is usually where this sort of cmdlet goes awry. I gather this is intended behavior to prevent malicious code from executing in the server environment. (source: [Fileless Malware Execution with PowerShell is Easier than You May Realize](https://securingtomorrow.mcafee.com/business/fileless-malware-execution-with-powershell-is-easier-than-you-may-realize/)

**Comment by rasa** [comment]
https://github.com/lukesampson/scoop/pull/2004

**Comment by rasa** [comment]
This issue appears to have been resolved. If not, please reopen this ticket, or let us know. Thanks!

**Comment by emredav** [comment]
Try this
` iex (new-object net.webclient).downloadstring('https://raw.githubusercontent.com/lukesampson/scoop/master/bin/install.ps1')`

**Comment by kayoroxa** [comment]
> 

Thank you soo muchh
