### ISSUE TITLE
Help with testing autoupdate

### ISSUE THREAD

**Issue by Guard13007** [lukesampson/scoop#1467]
I followed the [instructions here](https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate#add-checkver-to-a-manifest), however, it is not clear *which* manifest file I need to edit to test checkver at the end, or if that is even what needs to be run anymore, as when I ran it, there was no output and nothing changed.

**Comment by r15ch13** [comment]
What exactly do you mean? Each manifest/app has its own `checkver` and `autoupdate` information.

**Comment by Guard13007** [comment]
I mean that I'm not sure which manifest file I should be editing the version info on before running the command to check if auto-update works as intended. (For reference, I am trying to test [this manifest](https://github.com/Guard13007/ScoopBucket-ThirdParty/blob/master/love.json).)

**Comment by lukesampson** [comment]
By the way, if you're not committing to the main bucket or the extras bucket there's no need to use checkver or autoupdate. Having said that, we would appreciate apps like this in extras.

Since you're not currently using main or extras, you would need to run something like `~/scoop/apps/scoop/current/bin/checkver -dir ./ love` (if your current working directory is your `ScoopBucket-ThirdParty` source directory.

If you get output about the version then it's working, and you can add the `-u` parameter to do an update.

If you don't get output that means checkver couldn't find the JSON manifest, i.e. `love` in this case. So check the `-dir` parameter is pointing to the directory that contains the JSON manifest you want to check.

You can also do run it without a manifest, and it will check everything in the directory specified by `-dir`.

**Comment by Guard13007** [comment]
> By the way, if you're not committing to the main bucket or the extras bucket there's no need to use checkver or autoupdate.

Why?

> Having said that, we would appreciate apps like this in extras.

I intend to submit this and other manifests once I have them working with autoupdate, but I am making my own copy first so that if they are not accepted I will still have personal access to them.

Thank you for the detailed answer. I will try that, and assuming it works, I will close this and soon enough be opening a pull request for it. :D 

(I'm not sure how to word it, but I think the wiki needs a clarification for this.)

**Comment by Guard13007** [comment]
One related question since I'm about to potentially have two buckets with the same manifest in them, how does scoop decide priority?

**Comment by lukesampson** [comment]
>> Why?

Because checkver and auto-update are tools to help the Scoop team maintain the main and extras buckets. If you're maintaining your own bucket then you're free to maintain it however you like.

>> ... how does scoop decide priority?

If you don't pass an explicit bucket prefix (e.g. `scoop install extras/oraclejdk`), Scoop will check the main bucket first, then any other buckets in alphabetical order. The first match will be used.

**Comment by Guard13007** [comment]
Do you accept manifests without autoupdate?

(I am comfortable just using my own if you don't, but a project I'm making a manifest for only allows downloads from a browser by generating a unique URL for downloads and using a redirect.. so I'm hosting a copy of the file myself, and using that in the manifest, which would mean autoupdate wouldn't be functional unless I set up some other stuff (which I may do in the future, but requires active maintaining on my part).)

**Comment by lukesampson** [comment]
Yes we accept manifests without autoupdate, especially when it's hard or impossible to do an autoupdate as it seems in the case of this project you mentioned. It's better to have a potentially out of date manifest than none at all.

**Comment by Guard13007** [comment]
Cool, I'll be passing that one along as well then. :D
