### ISSUE TITLE
Add ability to install multiple architectures of a library.

### ISSUE THREAD

**Issue by tech4him1** [lukesampson/scoop#1473]
Some programs are dependent on a specific architecture of a library. For example, a program that is only available in a 32-bit version may also need the 32-bit version of the `openssl` library, which would be installed beside the 64-bit version already on the computer.

**Comment by lukesampson** [comment]
This could cause more problems than it solves. What if someone were to install 64-bit `openssl` and then `lynx`, which installed the 32-bit openssl?

Is there a package of Lynx that comes bundled with 32-bit OpenSSL? If not, you could download a 32-bit OpenSSL with an extra "url" in the Lynx manifest. This way, the Lynx install is self-contained because it has it's own copy of OpenSSL that shouldn't interfere with other programs.

**Comment by tech4him1** [comment]
> This could cause more problems than it solves. What if someone were to install 64-bit `openssl` and then `lynx`, which installed the 32-bit openssl?
I see your case there. I was looking at OpenSSL `dll`s specifically, which would not be a problem they have different filenames. That would not, however be the case for all apps.

**Comment by tech4him1** [comment]
> Is there a package of Lynx that comes bundled with 32-bit OpenSSL? If not, you could download a 32-bit OpenSSL with an extra "url" in the Lynx manifest. This way, the Lynx install is self-contained because it has it's own copy of OpenSSL that shouldn't interfere with other programs.

That would probably be the best option, the reason I was looking at this way originally was because of what you had said in #1375 about linking to other files for maintenance reasons instead of always being self-contained. That was kind-of a unique case, though.
