### ISSUE TITLE
mysql manifest no longer copies default config

### ISSUE THREAD

**Issue by Langmans** [lukesampson/scoop#1491]
This line:
```sh
#Copy provided sample file to live file location
cp $dir/my-default.ini $dir/my.ini
```
No longer works as `my-default.ini` is gone in the 5.7 windows distribution.

There's a default config file here: http://www.fromdual.com/mysql-configuration-file-sample

Also, mysql can't read config files if they have an UTF-8 BOM, it's possible that out-file is doing this. Use ASCII or [see this page on SO](http://stackoverflow.com/questions/5596982/using-powershell-to-write-a-file-in-utf-8-without-the-bom) for a solution.

**Comment by Jujunol** [comment]
This may be the problem I just encountered.

I just installed mysql via `scoop install mysql` and it started throwing the error:

`mysql: [ERROR] Found option without preceding group in config file [scoop install path]\scoop\apps\mysql\current\my.ini`

After looking at the ini that only contained:
```
[client]
user=root
```

## Fix
How I managed to fix it was by doing the following: 
1. `cd [scoop install path]\scoop\apps\mysql\current`
1. `del my.ini`
1. `rmdir data /s /q`
1. `mysqld --initialize-unsecure --basedir=. --datadir=.\data`
1. Then because I didn't have a mysql service `mysqld --install`
1. Finally `net start mysql`

**Comment by NemoStein** [comment]
About the
```
[ERROR] Found option without preceding group in config file ...\my.ini
```
The problem is that, for some esoteric reason, the encoding of the file includes a BOM (Byte Order Mark).
Just save the my.ini as UTF-8 (without BOM) solves the problem.

**Comment by rasa** [comment]
This issue belongs in the [Main](https://github.com/ScoopInstaller/Main) bucket. Unfortunately, we cannot move this issue on this end, so it is being closed.
If this is still an issue, please create a new issue in the Main bucket via https://github.com/ScoopInstaller/Main/issues/new?body=Moved+from+https%3A%2F%2Fgithub.com%2Flukesampson%2Fscoop%2Fissues%2F1491
