### ISSUE TITLE
remove php_extension.ini after uninstall

### ISSUE THREAD

**Issue by nueko** [lukesampson/scoop#1502]
Hi, i just created my [php-bucket](https://github.com/nueko/php-bucket). is there an post_uninstall script to execute after uninstallation to remove the file.ini created in persistent?

**Comment by lukesampson** [comment]
Users can pass `--purge` (`-p`) to `scoop uninstall` to remove all persistent data. If you want to do it manually you can use the `uninstaller` manifest property to run a script, but the general idea is that Scoop doesn't interfere with persistent data — it's up to the user.

**Comment by nueko** [comment]
the purge option doesn't work for me, i will try with the uninstaller.

**Comment by rrelmy** [comment]
@nueko great repository, I definitively have to give it a try 👍 
The uninstaller will not work for you, we better implement a new option for this.

@lukesampson The purge option will not work because the php extensions install them self into the persist storage of the `php` app.

A `post_uninstall` option could be used for this. But it could be worth it to discuss a new option for php extensions. Similar to psmodules.

Something like following.
scoop would handle the installation, uninstallation and activation of the extension.
``` json
{
    "php_ext": {"amqp": "php_amqp.dll"}
}
```

**Comment by lukesampson** [comment]
Ah okay. `php_ext` sounds like it might be easy to use, and `post_install` would cover more scenarios. Either or both would be fine by me.

**Comment by nueko** [comment]
Hi, I just think `post_uninstall` is insecure for this. as it saves the files on another package persistent-data.
`post_uninstall` script should not touch any other package persistent-data

**Comment by nueko** [comment]
fixed by creating uninstaller.

thanks.

nueko/php-bucket@3f4a7a9
