### ISSUE TITLE
Vim does not detect Python, Ruby or Lua

### ISSUE THREAD

**Issue by talha131** [lukesampson/scoop#1515]
I installed Python, Ruby, Lua and Vim via scoop. But running 

```
:echo has('python3')
:echo has('python')
:echo has('ruby')
:echo has('lua')
```

all return 0.

I can run Python from cmd and powershell. But Vim does not detect it. 

This [SO QA thread](https://stackoverflow.com/questions/4718122/how-to-enable-python-support-in-gvim-on-windows) suggests to check Vim and Python both have same build. I checked. Vim and Python both are 64bit.

Secondly, it suggests that Python version should match the python version with which Vim was compiled. It [turned out](https://github.com/vim/vim-win32-installer/) it is Python 3.5.3. So I added versions bucket, removed python and installed python35.

But it too had no effect. I also tried python27 but result remained the same.

Finally I did a regular install of Python 3.5.3 from its website, which fixed the issue. Result of 

```
:echo has('python3')
```

is 1.

But I would prefer to use scoop to manage all my apps. So it would be really awesome if Vim can detect Python, Ruby and Lua installed via scoop.

**Comment by lukesampson** [comment]
For me, Vim seems to detect Python installed with `scoop install python27`, but not with `scoop install python35`. I have no idea why.

**Comment by talha131** [comment]
I think the reason is path of python dlls is not added to the `PATH`. See this is my paths

![](http://i.imgur.com/R4q524L.png)

Now dlls are in this folder `C:\Users\talha\scoop\apps\python27\current` but this is not present in the `PATH`.

I added `C:\Users\talha\scoop\apps\python27\current` manually. Then Vim automatically detected python27.

So I think issue is path to dlls is not added to the path. `jsons` for Python versions needs to be fixed.

**Comment by lukesampson** [comment]
I've changed [python35](https://github.com/scoopinstaller/versions/blob/master/python35.json) so that it adds the `.../python35/current` directory to your path. Does that work for you if you re-install `python35`? I can `:echo has('python3')` and ':python3 print(1)` successfully now.

Python27 is detected for me as is, without adding `.../python27/current` to my path. Can you confirm that adding this directory to your path manually allows it to be detected by Vim?

This is the part I'm confused about, as if we could get Vim to recognise Python without adding the install directory to the path that would be ideal. Scoop tries to avoid polluting your path like that, preferring shims instead.

**Comment by talha131** [comment]
I will get back to you with my findings tomorrow.

**Comment by poulpoulsen** [comment]
hello,
unfortunately the problem occurs also with python 361 and gvim (newest downloads).
I used win81 64bit, added python\current\ to path.
But gvim do not detect python or python3.
Any clues?
Regards
Poul

**Comment by SimplyKnownAsG** [comment]
@lukesampson, it looks like that change was only done for python35 in the `versions` bucket. should `python.json` be removed from the scoop bucket?

**Comment by shyun3** [comment]
I had to stumble onto this issue to get Vim to recognize Python. Currently, only `python36` in the `versions` bucket seems to be compatible with the `vim` in the main bucket. Perhaps installing Vim should suggest installing the proper Python or maybe the all the Python apps should be updated so this issue won't arise?

**Comment by MadWombat** [comment]
I am currently having this problem. I have both vim and python installed from the main bucket. I have specifically added the python current directory to path. No luck at all.

**Comment by bucktower** [comment]
An update: I had this issue after `scoop install python vim` most recently, when I tried adding the YouCompleteMe plugin, which requires Python in Vim.

`:echo has('python')` and `:echo has('python3')` are both 0. If you try running a command invoking Python from within Vim like `python print('hello')`, Vim is unable to find the right .dll, but it'll tell you which one it's looking for.

This is because the most recent version of Python (installed by Scoop) is 3.7, and Vim is looking for `C:\Users\[USER]\scoop\apps\python\3.7.0\python36.dll`, not **python37.dll**. I tried installing Python 3.6 using the bucket in `versions`, but there was no **python36.dll** that I could find in the `C:\Users\[USER]\scoop\apps\python\3.6.5`. This is what I ended up doing that worked:

1. Give up. My first inclination was to duplicate **python37.dll** and rename it **python36.dll**, which is very hacky. Vim definitely picked it back up, but started spitting deprecation warnings, which I could then configure it to ignore, but this probably isn't a good idea since Python doesn't care too much about backward-compatibility, even though YouCompleteMe probably doesn't use too many advanced Python features.
2. Install Python 2.7: `$ scoop install python27`
3. Now go and edit your local PATH as pictured above to point to `C:\Users\[USER]\scoop\apps\python27\current`
4. You can try using `scoop reset` ([see here](https://github.com/lukesampson/scoop/wiki/Switching-Ruby-and-Python-Versions)) to set `$ python ...` to use Python 2.7. I think this worked for me, but it wouldn't work in the opposite direction resetting back to Python 3.6. Not a big deal because I'm not developing targeting Python.
5. Starting up Vim, everything works nicely.

**Comment by Elvyria** [comment]
Latest Vim version is finally looking for python37.dll, so adding `scoop\apps\python\current` to PATH now fixes the issue.
