### ISSUE TITLE
update-flow: uninstall after download

### ISSUE THREAD

**Issue by prasannavl** [lukesampson/scoop#1605]
Currently, scoop update flow works by uninstall the app, downloading, and then installing again. It would be smoother to recover from network errors, if does the downloading first, and then the uninstall followed by install. 

Obviously, not a priority issue, but thought it would be a good design flow to track.

**Comment by rasa** [comment]
+1

**Comment by r15ch13** [comment]
In my opinion, the update and install processes need to be reworked anyway.
When `scoop update *` fails somewhere down the line (permission errors because the program was running or download errors), it aborts the whole process while leaving you hanging with a broken app and the need to run it again. 

The function [`abort`](https://github.com/lukesampson/scoop/search?utf8=%E2%9C%93&q=abort&type=) has to be taken down! 🔫

**Comment by rrelmy** [comment]
I mentioned it in #1372 but never got that far …

**Comment by narnaud** [comment]
Any updates on that?
I have the issue from time to time, and it's always a pain to fix.

**Comment by rasa** [comment]
@narnaud Yes, I think there is general agreement that this is a flaw, that needs to be addressed. Please consider submitting a PR. My guess is the issue is pretty systemic, or we would have fixed it by now, as it's affected us all at one time or another.
