### ISSUE TITLE
request: distorm

### ISSUE THREAD

**Issue by yigitemres** [lukesampson/scoop#1625]
hi,
if it is possible, can you add distorm?

thx!

**Comment by rasa** [comment]
There are no .exes in the releases at https://github.com/gdabah/distorm/releases. What, exactly, are you looking to install?

**Comment by rrelmy** [comment]
@rasa There are some :-)
![image](https://user-images.githubusercontent.com/442683/28534294-85cc299e-70a0-11e7-9098-951766c87a9e.png)

@yigitemres 
The manifest should be pretty easy to write if you want to try it 😉 
Take a look at the manifest for [hugo](https://github.com/lukesampson/scoop/blob/master/bucket/hugo.json) which also uses github releases.
You can remove the `hash` inside `autoupdate` because distorm does not release official hashes

**Comment by r15ch13** [comment]
@rrelmy these are Installers which only install some stuff into `...\python\3.6.2\` and `...\python\3.6.2\site-packages` (or python 2) :smile:

**Comment by rrelmy** [comment]
Oh, sorry. I didn't check that.

I am not a python guy, but I believe we could add the path to those library files to the `PYTHONPATH` env variable.
https://stackoverflow.com/a/19917565/1143768

Something similar is done with [python-exp](/lukesampson/scoop/blob/master/bucket/python-exp.json#L105). But don't ask me why they use the registry instead of the environment variable …

**Comment by rasa** [comment]
I wrote the manifest, and installed it, but no .exes are found in the extracted files, as per above. Not sure how to proceed.

**Comment by yigitemres** [comment]
found replacement: capstone-engine.org
