### ISSUE TITLE
Scoop update yarn (already exists) exits with error

### ISSUE THREAD

**Issue by IAMtheIAM** [lukesampson/scoop#1758]
When re running `scoop install yarn` and yarn is already installed, scoop exists with an error ` yarn 1.2.0 is already installed. Use scoop update yarn to install a new version.`

Then it exists with an error. Instead it should be a warning, and continue executing the next script.

Or better yet, automatically run "scoop update yarn". But either way, it should not produce an error.

The use case:

my script does this:
```
Install scoop
Install yarn
```

If I run once, it succeeds. If I run twice, now it fails.

So I have to do this
```
Install scoop
Uninstall yarn
Install yarn
```

That does not seem like the right way to handle it. If scoop didnt' exit with an error when it tries to install something that already exists, then I wouldn't need to uninstall it first. Let me know...

**Comment by IAMtheIAM** [comment]
It seems my scoop install got corrupted someone. I tried `scoop uninstall scoop` and it failed. So i just deleted scoop, cleared the PATH of scoop, and resinstalled. Now it works fine.

**Comment by r15ch13** [comment]
Yeah, that has something to do with [scoop-install.ps1](https://github.com/lukesampson/scoop/blob/master/libexec/scoop-install.ps1) and the [abort](https://github.com/lukesampson/scoop/search?utf8=%E2%9C%93&q=abort&type=) function. It's a lot of work to remove it because it blocks all kind of commands.

Running `scoop install yarn wget` to install multiple programs, would have run perfectly fine by just skipping the already installed ones.
https://github.com/lukesampson/scoop/commit/a3e84bd5045c141d0ec0e5fcea22ab9685ebde53 should fix the issue with single program installations.

**Comment by IAMtheIAM** [comment]
Awesome, thanks for that quick fix! Is there a way I can get that update or do I have to wait for a next release?

**Comment by r15ch13** [comment]
just run `scoop update`

**Comment by IAMtheIAM** [comment]
beautiful! works like a charm - thanks again.
