### ISSUE TITLE
System copy/paste does not work with neovim package

### ISSUE THREAD

**Issue by youngmit** [lukesampson/scoop#2021]
After installing the neovim package, attempts to copy to the system clipboard fail. This is pretty easy to reproduce:
```
scoop install neovim
nvim
"*yy
```
A command window for win32yank.exe will pop up and not go away, unless killed explicitly. Any text entered into the command window will end up on the clipboard when it is closed.

Instead, one would expect no window to pop up, and the yanked text to end up on the clipboard.

"Installing" neovim from the regular zip file works just fine, unless the neovim scoop package has been installed with scoop, since the shim for win32yank.exe supersedes the win32yank.exe included in the stock neovim distribution. So, it would appear that something in the win32yank.exe shim that comes with the neovim package is preventing communication between the yank tool and neovim.

**Comment by wsw0108** [comment]
no need to add 'win32yank.exe' to bin property

**Comment by tahir-hassan** [comment]
I was still having this same issue of the win32yank window hanging there.  I have neovim and win32yank scoop packages installed.  I fixed it by including the following in my `init.lua` file:

```lua
vim.g.clipboard = {
  copy = {
    ["+"] = "win32yank.exe -i --crlf",
    ["*"] = "win32yank.exe -i --crlf",
  },
  paste = {
    ["+"] = "win32yank.exe -o --lf",
    ["*"] = "win32yank.exe -o --lf",
  },
}
```

I am not sure why it works because neovim can already find win32yank.exe (the path in the hanging window has `C:\Users\username\scoop\apps\win32yank\current\win32yank.exe`), but perhaps with the above configuration, neovim uses a win32yank executable of its own.
