### ISSUE TITLE
Add zstd

### ISSUE THREAD

**Issue by alejandro5042** [lukesampson/scoop#2066]
[zstd](https://github.com/facebook/zstd) is a popular and effective compression utility with binaries on [GitHub releases](https://github.com/facebook/zstd/releases).

I'm happy to add this utility and others for us. Is there a template for how to add simple exes from zips listed in GitHub releases and have them auto-update?

**Comment by rasa** [comment]
Its already in versions: https://github.com/scoopinstaller/versions/blob/master/7zip-zstd.json

**Comment by alejandro5042** [comment]
But that's not really it. I want `zstd.exe` not `7z.exe` or `7zg.exe`.

Finally, `7zip-zstd` fails to install for me:

```
> scoop install 7zip-zstd
Installing '7zip-zstd' (17.01-v1.3.2-R1) [64bit]
Loading 7z1701-zstd-x64.exe from cache
Checking hash of 7z1701-zstd-x64.exe... ok.
Running installer... done.
Linking ~\scoop\apps\7zip-zstd\current => ~\scoop\apps\7zip-zstd\17.01-v1.3.2-R1
Creating shim for '7z'.
Can't shim '7z.exe': File doesn't exist.
```

And it also gives me a UAC prompt, which I thought was against the idea of the scoop project.

**Comment by rasa** [comment]
Oops, my mistake. Sorry for the confusion.

**Comment by yigitemres** [comment]
@alejandro5042 if you look scoop wiki and other manifests you can easily create manifest file. you just create file and make initial pull request. we will be happy to help you. 👍

**Comment by alejandro5042** [comment]
Thank you! I'll bookmark your pull request in case I have more tools to add from GitHub releases.

Note; It might be good to add a few examples to the README for people to have a starting point on adding new packages. Pick 4-5 packages that are unique in some way and then link to the rest of the documentation in the Wiki. It would help first-time contributors like me :)

**Comment by yigitemres** [comment]
Firstly, I'm "sorry" to creating pull request. You should do it but I'm waiting 24 hours and after that I can't resist. 😄 The wiki has examples but its not easily understandable (IMO) until start to creating manifest.
https://github.com/lukesampson/scoop/wiki/App-Manifests

I think that learning with trial and error is good here because @r15ch13 and @rasa (and others too) will warn you when making mistakes and help on the creating manifest. I'm also new here too and they helped me everytime. 🥂I'm thinking creating a newbie guide for creating app manifest with examples and screen shots. (Only for portable apps and maybe with some post_install/pre_install examples, not with installers at the moment.)

**Comment by rasa** [comment]
This ticket can be closed.
