### ISSUE TITLE
GraphicsMagick

### ISSUE THREAD

**Issue by ekoeryanto** [lukesampson/scoop#2086]
Halo, I think we miss GraphicsMagick here.
here is url to create the manifest if any body has some time to.
ftp://ftp.graphicsmagick.org/pub/GraphicsMagick/windows/

**Comment by yigitemres** [comment]
Manifest file is ready but I cannot test it because SourceForge downloads are still broken!

**Comment by excitoon** [comment]
Hi, @yigitemres . Can you check if this patch will fix sourceforge? I experienced problems with sourceforge often and I made a fix for myself, but I'd like to check if it helps to anybody else:
https://github.com/excitoon/scoop/commit/c30e081c0acdf952b0bb45db1f9a3a780140a7d5

**Comment by yigitemres** [comment]
@excitoon It's not working for me. Instead of downloading exe, it downloads html/js file. I change manifest url to every possible combination (in case of messed up) and there is no change! (.exe , .exe#/dl, .exe#/dl.7z) If anybody can download from SourceForge without having problem, feel free to creating pull request. 
```
<!doctype html>
<!-- Server: sfs-consume-1 -->
<html class="no-js" lang="en">
    <head>
     ...
```

**Comment by excitoon** [comment]
I would recommend you to strip `/download` from your URLs. See https://github.com/lukesampson/scoop-extras/blob/master/winmerge.json as a reference.

**Comment by yigitemres** [comment]
@excitoon Silly me! I'm using "download.sourceforge" instead of "download's'". It's downloaded. Thx! 🥂
