### ISSUE TITLE
64 Bit PHP

### ISSUE THREAD

**Issue by ntwb** [lukesampson/scoop#235]
The PHP manifest was just updated to include 64 Bit PHP in #234

PHP 64 Bit was added previously as a standalone manifest in `scoop-extras`, I cannot remember the reason why, "I think" it was in regard to 64 bit stability, I honestly cannot remember.

https://github.com/lukesampson/scoop-extras/blob/master/php64bit.json

We should either 1) Remove the `php64bit.json` manifest from `scoop-extras` or 2) Remove the 64 bit architectural from the `scoop` `php.json` manifest.

Is PHP 64 Bit now stable on Windows?, If so we do option 1 above, if not option 2. Thoughts?

**Comment by gutierri** [comment]
@lukesampson Hey!?

**Comment by lukesampson** [comment]
Sorry I didn't respond sooner, Gutierri.

And sorry to drag the chain here again, but I just had a quick look at the PHP website now and the thing that I want to be careful about is that 64-bit PHP is described as "experimental" on Windows. I want to be careful that non-experts (like myself) don't get into trouble by installing an unreliable version of PHP when the 32-bit version would work better.

Maybe the "experimental" thing is overblown, and it actually works great? I'll defer to you guys here. If that's the case then I'd be happy to merge this, so we get automatic 64-bit version for Apache and PHP.

If however the 64-bit version is still a bit risky, then I think maybe the thing to do is have a new `apache64.json` as a separate manifest, and keep `php64.json`, so that experts can install these if they want, and it just works (in 32-bit mode) for everyone else.

**Comment by gutierri** [comment]
@lukesampson Ok!

But I never had problems with the 64bit version of PHP on Windows. But we can see what can be done.

**Comment by lukesampson** [comment]
@gutierri If you want to update [apache64bit](https://github.com/lukesampson/scoop-extras/blob/master/apache64bit.json) and [php64bit](https://github.com/lukesampson/scoop-extras/blob/master/php64bit.json) with these changes you've made, I'll merge those in.

I think that's probably the safest thing to do for now, unless you're confident that 64-bit Apache+PHP will work fine for everyone.

**Comment by gutierri** [comment]
@lukesampson Ok!

It would be nice also organize scoop packages, especially those alternative versions of other packages.

Creating a standard for this, for example:
<kbd>php_x64</kbd>
<kbd>apache_x64</kbd>

**Comment by deevus** [comment]
@gutierri @lukesampson How about we mark them as experimental as well:
<kbd>php_x64-experimental</kbd>
<kbd>apache_x64-experimental</kbd>

**Comment by lukesampson** [comment]
Hmmm, I can see the value in showing that it's experimental, but it seems a bit hard to type. I think it's nice to read too when apps have nice short names rather than be too verbose.

Another downside of making it too explicit that this is 64-bit is that if you're looking through the list of apps and see `php_x64` you might think "where's the 64-bit mysql?" or something similar.

And I can't see it happening very often that a program would be available in separate 64-bit version that doesn't work very well. So, by creating a convention, I think we might be solving a problem that doesn't yet (and may never) exist.

**Comment by gutierri** [comment]
We need conventions!

**Comment by lukesampson** [comment]
Why's that? I agree conventions are good, but creating them for situations that are rare is counter productive because it's just another rule we have to remember. Do you disagree with my points? I'm open to persuasion, I just need arguments to convince me that forcing people to use clunky app names is worth it.

**Comment by gutierri** [comment]
I think of something as simple as what already was. Packages 64bit "namehere_x64". Simple and perhaps solve our problems.

Or create an option when installing

@lukesampson?

**Comment by lukesampson** [comment]
There already is an option when installing to choose your architecture, with the `--architecture` or `-a` flag. Scoop automatically gives you the best architecture for your system if you don't tell it otherwise.

There is a bit of backstory here, I'll go over it again. The thing with PHP is that their 64-bit builds are experimental so are not recommended for production use (last I checked). We don't want to automatically give experimental builds to people, which is why there's a separate package for 64bit, and people have to explicitly choose it if they know what they're doing. Once PHP gets their 64-bit build to a stable state we can probably just forget about this problem. Most people should be fine the 32-bit build for now.

This is not normative, it's a workaround and shouldn't happen very often, if ever again.

So, let's stick with the `[app]64bit` convention for now because it matches the `--architecture` flag.

**Comment by moigagoo** [comment]
@gutierri I totally agree with @lukesampson. A convention like this creates more problems than it solves.

In fact, is there really a problem? Does the name php64bit really hinder anyone's workflow? How's php_x64-experimental better? Is x64 more informative than 64bit, and is the experimental bit useful?

Honestly, I can't see reasonable answers to these questions.

**Comment by gutierri** [comment]
OK!
On Apr 9, 2015 1:10 AM, "Konstantin Molchanov" <notifications@github.com>
wrote:

@gutierri <https://github.com/gutierri> I totally agree with @lukesampson
<https://github.com/lukesampson>. A convention like this creates more
problems than it solves.

In fact, is there really a problem? Does the name php64bit really hinder
anyone's workflow? How's php_x64-experimental better? Is x64 more
informative than 64bit, and is the experimental bit useful?

Honestly, I can't see reasonable answers to these questions.

—
Reply to this email directly or view it on GitHub
<https://github.com/lukesampson/scoop/issues/235#issuecomment-91110601>.

**Comment by gutierri** [comment]
:)
