### ISSUE TITLE
Need to install Rstudio who ask to install R first

### ISSUE THREAD

**Issue by hareramcse** [lukesampson/scoop#2676]
Hi Guys, I need to install Rstudio. once i run Rstudio it ask to install R first. i installed R from here by using scoop install r command in powershell. Now in that json file there is note section. can any please explain what it means. i am not able to run R once i install it through scoop. so my rstudio is not running. any help will be apreciated.

**Comment by r15ch13** [comment]
Open `RStudio`, go to `Tools`, `Global Options` and check if the correct `R Version` is selected on the `General` Tab.

Should look like this:
![image](https://user-images.githubusercontent.com/432127/47030668-6a032980-d16e-11e8-8a09-33f149aacca8.png)

Running `R` from PowerShell only works if you type `rterm` because of the alias (described in the notes)

**Comment by hareramcse** [comment]
I cant open the rstudio as it asks first choose the R installation to open it. i have already installed R through scoop then it should not ask. but it seems there is something missing while installing R through poweshell. i see some message in notes section of it. that i am not getting what does it mean.

**Comment by Ash258** [comment]
Notes only say how you need to run r

https://github.com/lukesampson/scoop/blob/d71cd151c6df32f3baa0987bb802bcc440280c7e/bucket/r.json#L23-L31

**Comment by hareramcse** [comment]
Thank you so much for the help. after pointing out to the R installation directory, i am able to launch rstudio now.  Thank again.
