### ISSUE TITLE
cygwin@2.895 is installed in wrong places.

### ISSUE THREAD

**Issue by crocket** [lukesampson/scoop#2727]
cygwin@2.895 is installed in

```
C:\Users\User\scoop\apps\cygwin\2.895\root\root\bin
```

instead of

```
C:\Users\User\scoop\apps\cygwin\2.895\root\bin
```

I see

```
C:\Users\User\scoop\persist\cygwin\root\root
```

**Comment by r15ch13** [comment]
This might be fixed with the new changes. Please try again.
Persisted directory should only contain:

![image](https://user-images.githubusercontent.com/432127/47962981-46bcf300-e025-11e8-9052-92e5d5ecc0e3.png)

And the app directory should look like this: 

![image](https://user-images.githubusercontent.com/432127/47962991-7bc94580-e025-11e8-9112-cb2355ce292a.png)

**Comment by crocket** [comment]
I tried again. This issue has been fixed.
