### ISSUE TITLE
[Request] Add vcpkg

### ISSUE THREAD

**Issue by Swoorup** [lukesampson/scoop#2946]
C++ package manager

**Comment by Ash258** [comment]
vcpkg work similar way as scoop. It means, there is no release and they manage updates using git pulling.

Creating vcpkg manifest would be easy to install. It should be just nighly version with these steps:

1. URL with actual master zip extracting
1. Install
    1. Run steps from [Quick Start](https://github.com/Microsoft/vcpkg#quick-start) in installer.script
        1. Run bootstrap
        1. Run integrate install

But problem is with updating. Updating with force parameter would be possible, but it would be not efficient, since it will be installed on every updating. 

Updating using git pull is best way, but require register alias (like `scoop upvcpkg`), which should stand for `Push-Location (scoop prefix vcpkg); git pull; Pop-Location`. And it need to be executed manually.

**Comment by ras0219-msft** [comment]
To update you'll need to:
```
>git pull
>./bootstrap-vcpkg
>./vcpkg upgrade --no-dry-run
```

**Comment by rasa** [comment]
This issue belongs in the [Main](https://github.com/ScoopInstaller/Main) bucket. Unfortunately, we cannot move this issue on this end, so it is being closed.
If this is still an issue, please create a new issue in the Main bucket via https://github.com/ScoopInstaller/Main/issues/new?body=Moved+from+https%3A%2F%2Fgithub.com%2Flukesampson%2Fscoop%2Fissues%2F2946
