### ISSUE TITLE
Add scoop to Wikipedia List of software package management systems

### ISSUE THREAD

**Issue by Konrad90** [lukesampson/scoop#2965]
Is scoop missing here?
https://en.wikipedia.org/wiki/List_of_software_package_management_systems#Windows
I'm not sure how and where to add it myself the right way.

**Comment by Calinou** [comment]
Before creating a page for Scoop, please make sure it meets the [Wikipedia notability guidelines](https://en.wikipedia.org/wiki/Wikipedia:Notability).

**Comment by shoogle** [comment]
It is indeed missing from that list. Scoop developers [cannot ask you to write anything on Wikipedia about Scoop](https://en.wikipedia.org/wiki/Wikipedia:Conflict_of_interest), but presumably they would like it if you did :wink:.

By the way, if you just want to mention Scoop in that artice then the notability guidelines [do not apply](https://en.wikipedia.org/wiki/Wikipedia:Notability#Notability_guidelines_do_not_apply_to_content_within_an_article). They only apply if you want to create an article specifically about Scoop.

**Comment by shoogle** [comment]
If anybody did want to add Scoop, all they would need to do is click the [ [edit](https://en.wikipedia.org/wiki/List_of_software_package_management_systems#Windows) ] button next to the [Windows section](https://en.wikipedia.org/wiki/List_of_software_package_management_systems#Windows) and put an entry in there. The best place to put it is probably immediately after Chocolatey as they are very similar, the main difference being that [Scoop is in the spirit of Homebrew](https://github.com/lukesampson/scoop#inspiration) rather than `apt-get`, and it doesn't use Nu-Get. Other differences are explained [here](https://github.com/lukesampson/scoop/wiki/Chocolatey-Comparison).
