### ISSUE TITLE
different filenames per architecture to the same name

### ISSUE THREAD

**Issue by sakai135** [lukesampson/scoop#303]
Is there a way to install binaries to the same name when each architecture has a different filename in the URL? 

Specifically, I have a manifest like the one below. Since the architecture is in the filename, they get downloaded to different files, and AFAIK you can't have separate `bin` under the `architecture`.

```json
{
	"version": "0.2.0-rc1",
	"architecture": {
		"64bit": {
			"url": "https://github.com/docker/machine/releases/download/v0.2.0-rc1/docker-machine_windows-amd64.exe"
		},
		"32bit": {
			"url": "https://github.com/docker/machine/releases/download/v0.2.0-rc1/docker-machine_windows-386.exe"
		}
	},
	"bin": [
		["docker-machine_windows-amd64.exe", "docker-machine"]
	]
}
```

**Comment by lukesampson** [comment]
There is a semi-secret `pre_install` step that runs before the shims are set-up for your bins—would it work to use this to rename the `docker-machine...` exe to just `docker-machine` so that when the shim is made it's the same filename?

There's an example `pre_install` in the [gow](https://github.com/lukesampson/scoop/blob/master/bucket/gow.json) manifest for reference.

**Comment by sakai135** [comment]
Cool, I think that will work. Thanks.
