### ISSUE TITLE
Request: zsh

### ISSUE THREAD

**Issue by stuaxo** [lukesampson/scoop#3053]
Request for zsh, hopefully Oh my zsh will work inside it.

**Comment by Calinou** [comment]
Shouldn't one install zsh in the Windows Subsystem for Linux instead?

**Comment by stuaxo** [comment]
I'm using a work machine, although I'm a developer it is locked down.

**Comment by stuaxo** [comment]
I'm using bash for Windows, I'd prefer to use zsh built for mingw

**Comment by okonomiyaki3000** [comment]
@stuaxo I think you're barking up the wrong tree. If you want to use zsh on Windows, you should use MSys2. It includes pacman which lets you install zsh and a lot of other things. oh-my-zsh also works. It's what I use on my work PC because I agree with you, the usual Windows command line is an abomination.

**Comment by rasa** [comment]
Closing as this issue is stale. Please reopen if this is still an issue.

**Comment by stuaxo** [comment]
Will reopen if I find a build of zsh it's easy to integrate
