### ISSUE TITLE
Duplicate taskbar icon when pinning a desktop app to taskbar

### ISSUE THREAD

**Issue by farzadmf** [lukesampson/scoop#3271]
Hi,

I have a minor problem with the apps that I pin to the taskbar on Windows 10 version `1709`

Taking **Azure Data Studio** as an example: here's what I do:
- I install using `scoop install azuredatastudio`
- I open the start menu and start searching for "Azure ..."
- I see the **Azure Data Studio** icon
- I right click and select **Pin to Taskbar**

Now, whenever I click on the taskbar icon, when the application starts, it creates a duplicate icon in the taskbar, as you can see below:
![image](https://user-images.githubusercontent.com/5768792/55076458-ce0a1200-506b-11e9-98be-9697cb70faa4.png)

So, it's a bit confusing, because I'm used to looking at the taskbar icons to see if I have a window open for a certain application and click on it to switch to that window, but now, when I look at the "original" pinned one, I see that it's not running, and I click on it, and it creates a new window grouped with the "duplicate" icon in the taskbar
![image](https://user-images.githubusercontent.com/5768792/55076698-761fdb00-506c-11e9-9882-fda0597f01c4.png)

It's not a huge issue, but it would definitely help if the pinned icon would behave like other pinned icons

**Comment by Ash258** [comment]
This depends on application. You just pinned shortcut to `$env:SCOOP\apps\<app>\current\exe` file.

But some applications cannot handle these symlinks and are just executed in `$env:SCOOP\apps\<app>\<specific version>\exe` instead of current alias, which result in duplicate icon (one for current, one for version specific). There is no much scoop can do about it.

**Comment by farzadmf** [comment]
Thank you @Ash258 for your answer and the clarification. So, is there a workaround or something I can do? Because I tried to directly pin the `exe` file in `<specific version>`, but that didn't work either.

**Comment by Ash258** [comment]
You could try to pin both of them (pin from start; execute the pinned one from taskbar; pin duplicate one if occured) and see what target they point to. There should be something changed.

Because if you pin both of them you should see two shortcuts inside `C:\Users\<User>\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar`, and they should point to different exe file

**Comment by farzadmf** [comment]
Thank you @Ash258 for your suggestion 👍 ; it seems that pinning the "duplicate" one does the trick. Just one more question: is there a way in `scoop` to clean up the old versions? Because `current` points to the latest version, but the older versions are still there. Do I need to remove them manually?

**Comment by Ash258** [comment]
`scoop cleanup *` for all apps or just `scoop cleanup azuredatastudio` see: https://github.com/lukesampson/scoop/wiki/Commands

**Comment by farzadmf** [comment]
Thank you @Ash258 for your help. I'm going to close this issue as it's resolved for me

**Comment by dlong500** [comment]
@Ash258 Pinning the duplicate won't fix the problem once the app in question gets updated to another version.  The only thing pinning the duplicate does is pin a shortcut to the actual version folder rather than the `current` symbolic link.  So once the app is updated you'll be left with a pinned shortcut to the older version.

Unfortunately it seems like the Windows taskbar just doesn't work well with symbolic links.  In theory there could be a programmatic workaround that would allow for scripting a replacement for a pinned item after scoop updates an app, but I'm not sure Windows has any scriptable options for messing with pinned apps.

It definitely is super annoying (I experience the issue with WinSCP).  It's enough that I've decided to abandon scoop for this app and just manually update it.  Having to re-pin the app is annoying but not a huge deal, but losing all the info in the jumplist for the pinned app is too much to deal with every time the app is updated.

**Comment by he3als** [comment]
It is inconvenient, but you can re-pin the latest version each update instead of the 'current' symbolic link as a workaround.

**Comment by kul-sudo** [comment]
Any updates?

**Comment by fbis251** [comment]
@farzadmf I'd recommend editing the paths in the link that is created for the app you're trying to pin to the taskbar.

I installed Thunderbird via scoop, opened the application and pinned the program to the taskbar. The taskbar shortcut that got created was specifically for version `115.4.1`, the path was `C:\Users\<user>\scoop\apps\thunderbird\115.4.1\thunderbird.exe`

I used the following steps to make sure that the `current` path is used instead

- Right click the taskbar icon
- Right click the application name
- Click Properties
- Change the target to the `current` path, `C:\Users\<user>\scoop\apps\thunderbird\current\thunderbird.exe`
- Change Start in to the `current` path, `C:\Users\<user>\scoop\apps\thunderbird\current`
- Click OK

![image](https://github.com/ScoopInstaller/Scoop/assets/1300530/98f24877-ac57-456b-a2d9-2518b96fa402)
![image](https://github.com/ScoopInstaller/Scoop/assets/1300530/46a60b92-7746-45a2-bd5a-971e4906f33c)

Hope that helps you and anyone else finding this issue through a search engine like I did

**Comment by farzadmf** [comment]
Thank you @fbis251 for the explanation AND the screenshots.

It's been a few years since I last used Windows (the issue itself is 5y old 😮) , but I vaguely remember that this was actually what I ended up doing.

**Comment by kul-sudo** [comment]
> @farzadmf I'd recommend editing the paths in the link that is created for the app you're trying to pin to the taskbar.
> 
> I installed Thunderbird via scoop, opened the application and pinned the program to the taskbar. The taskbar shortcut that got created was specifically for version `115.4.1`, the path was `C:\Users\<user>\scoop\apps\thunderbird\115.4.1\thunderbird.exe`
> 
> I used the following steps to make sure that the `current` path is used instead. Make sure you use your actual username in place of the `<user>` placeholders I used in the text and screenshots below
> 
> - Right click the taskbar icon
> - Right click the application name
> - Click Properties
> - Change the target to the `current` path, `C:\Users\<user>\scoop\apps\thunderbird\current\thunderbird.exe`
> - Change Start in to the `current` path, `C:\Users\<user>\scoop\apps\thunderbird\current`
> - Click OK
> 
> ![image](https://github.com/ScoopInstaller/Scoop/assets/1300530/98f24877-ac57-456b-a2d9-2518b96fa402)
> ![image](https://github.com/ScoopInstaller/Scoop/assets/1300530/46a60b92-7746-45a2-bd5a-971e4906f33c)
> 
> Hope that helps you and anyone else finding this issue through a search engine like I did

This is a working solution. Thanks for your help.

**Comment by dlong500** [comment]
@fbis251 Unfortunately that isn't a solution that applies to all apps facing this issue.  For WinSCP if you make the edits as you suggest then every time you spawn a WinSCP connection the taskbar adds a separate icon so you end up with two taskbar items (one for the base app and another for actual session connections).  This makes it frustrating visually because not everything is grouped together, which of course is the whole point of taskbar grouping.  Scoop still has some work to do to handle taskbar entries for apps that spawn new instances.  Modifying the shortcut to point to the "current" path is only helpful for apps that don't ever spawn new instances (i.e. run in single-instance mode).

**Comment by haku527** [comment]
Some apps can handle symlink, pinning `~/scoop/app/<appname>/current/app.exe` won't get duplicate taskbar icon; just like `firefox`.

Some are not, like `wezterm`, when you pinned `~/scoop/app/<appname>/current/app.exe` from start menu, another icon `~/scoop/app/<appname>/<latest version>/app.exe` shows up when you click the pinned app.

So **the workaround** is pin the `<specific version>` taskbar icon for those apps, and redo everytime those got upgraded.

**Comment by stablum** [comment]
I'm also experiencing the issue of pinning an installed executable to taskbar and then seeing a duplicate firefox taskbar entry when run. 

Issue happens also when pinning the specific current version firefox executable.

So, this hasn't been solved yet, please do something as this is quite an annoyance.
