### ISSUE TITLE
scoop does not show the information about added path

### ISSUE THREAD

**Issue by nightroman** [lukesampson/scoop#349]
I have found this minor issue on testing this [PR](https://github.com/lukesampson/scoop/pull/348). It proposes to replace "bin" (shims) with "env_add_path" (adding to the path) in *invoke-build.json*.

With "bin" (shims) scoop tells what shims are installed:

    > scoop install invoke-build
    installing invoke-build (2.12.0)
    loading http://nuget.org/api/v2/package/Invoke-Build/2.12.0#.zip from cache...
    checking hash...ok
    extracting...done
    creating shim for Invoke-Build
    creating shim for Invoke-Builds
    invoke-build (2.12.0) was installed successfully!

And then on uninstalling scoop tells they are removed:

    > scoop uninstall invoke-build
    uninstalling invoke-build (2.12.0)
    removing shim for Invoke-Build
    removing shim for Invoke-Builds
    invoke-build was uninstalled

But on installing with "env_add_path" scoop does not tell anything about adding the path:

    > scoop install invoke-build
    installing invoke-build (2.12.1)
    downloading http://nuget.org/api/v2/package/Invoke-Build/2.12.1#.zip...done
    checking hash...ok
    extracting...done
    invoke-build (2.12.1) was installed successfully!

At the same time on uninstalling it tells about removing the path (good):

    > scoop uninstall invoke-build
    uninstalling invoke-build (2.12.1)
    removing ~\appdata\local\scoop\apps\invoke-build\2.12.1 from your path
    invoke-build was uninstalled

So the suggestion is to show the information about added path on installing.

**Comment by nightroman** [comment]
And a similar note about added / removed environment variables (`"set_env"`). It all works fine (added, removed), scoop just does not show these bits of information.

**Comment by lukesampson** [comment]
One of the goals of scoop is not to pollute your path with all the programs you install, so that's why there are shims and the shim directory is in your path already.

I think it's helpful to see in the output what new commands are available, but it's less useful to see that a path was added—there's not much information that end users can act on.

As a package author you might be interested to see this information, but we're interested in creating a pleasant experience for end-users too, and I think the cognitive burden introduced by announcing minor details (such as a path being added) is detrimental to that experience.

**Comment by nightroman** [comment]
No problem at all

I just would like to add that I am interested in this information not as a package author. I'd like to know what changed on installation of apps because this gives me a tip on how to use the tool. If scoop tells me that a path is added then I go to this path and see the available commands. If it tells me nothing I have to guess.
