### ISSUE TITLE
Electron's NSIS installer has been broken

### ISSUE THREAD

**Issue by linsui** [lukesampson/scoop#3532]
It seems that all Electron's NSIS installer ($PLUGINSDIR/app-32|64.7z) has been broken.

I test with standardnotes and get

```
Extracting dl.7z ... Could not find '$PLUGINSDIR'! (error 16)
所在位置 D:\scoop\apps\scoop\current\lib\core.ps1:506 字符: 9
+         throw "Could not find '$(fname $from)'! (error $($proc.ExitCo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find '$PLUGINSDIR'! (error 16)
   :String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find '$PLUGINSDIR'! (error 16)
```

https://github.com/lukesampson/scoop-extras/issues/2355

**Comment by D-W-X** [comment]
I have tested showing that it may be 7z's fault,  or the path.

the path should as "...\scoop\apps\7zip\current\7z.exe x "...\dl.7z" -o"..." -y -ir!$PLUGINSDIR\*"  instead of *\scoop\apps\7zip\current\7z.exe x "...\dl.7z" -o"*" -y -ir!**\\**$PLUGINSDIR\*" .

In `listen1desktop` ,`extras` , its `listen1desktop.json` is "extract_dir": "\\$PLUGINSDIR" !

Or in the scoop, `...\scoop\lib\decompress.ps1`, function `Expand-7zipArchive` ,line 71 , add the error path (contains more `\\` ) in 7z's command line, maybe should do some check?

**Comment by linsui** [comment]
Yeah, it works! :+1:

**Comment by D-W-X** [comment]
According to `postman`, `extra bucket`, line 18:
    `    "extract_dir": "lib\\net45",` ,
 it just the `listen1desktop.json` 's faluts , 

BUT if  `scoop` has some check here I think it will be better!

**Comment by qcts33** [comment]
`"extract_dir": "\\$PLUGINSDIR"` is always there since the creation of `listen1desktop.json`. 
I think `scoop` have change it behavior when dealing with the `extract_dir`

**Comment by linsui** [comment]
Yeah, I guess the bug is imported here https://github.com/lukesampson/scoop/commit/2fafcb880a178c949b6295c52d9124f932e2905c#diff-14c7e84ec142b387b7cc5db2852adbe4
