### ISSUE TITLE
Allow running in git bash

### ISSUE THREAD

**Issue by dre1080** [lukesampson/scoop#354]
Currently, running scoop in git bash fails. Possible to allow running inside git bash like chocolatey?

**Comment by deevus** [comment]
Hi there

Can you provide some more information? What happens when you try to run Scoop inside Git Bash?

Thanks

**Comment by dre1080** [comment]
I'm running Windows 8.1, Git 1.9.5

When I try run `scoop help` in Git bash:
```
scoop: command not found
```

In the `shims` directory, there's only `scoop.cmd` and `scoop.ps1` file.

When I run `scoop.cmd help` in Git bash:
```
.../appdata/local/scoop/shims/scoop.cmd: line 1: @powershell: command not found
```

The new `choco` command can run in cmd and Git bash.

**Comment by deevus** [comment]
This seems to be an issue with evaluating commands in Bash. Git Bash happily executes exe files without having to explicitly say "powershell.exe" but this is not so for ps1 files.

Please try putting the following in your `~/.bash_profile`:

```
alias scoop="powershell scoop.ps1"
```

You'll need to restart Git Bash or run `source ~/.bash_profile`

**Comment by deevus** [comment]
@lukesampson What do you think about adding the above to `bash_profile` by default?

**Comment by lukesampson** [comment]
That sounds good, @deevus.

**Comment by deevus** [comment]
@dre1080 If you haven't fixed this yet, update scoop (`scoop update`) and run `scoop reset scoop`

Scoop should then work in Git Bash

**Comment by nightroman** [comment]
Does this mean that on every machine scoop creates or updates this file? If yes, is not it a little bit intrusive? scoop is nice because it is not intrusive, it is the important feature.

Some people do not use bash and may not want to have this file (me). Some people use bash and may not want their profile to be updated without their consent. Just a thought...

**Comment by nightroman** [comment]
> `| out-file ~/.bashrc -en oem -append`

If the existing file does not have the last empty line then the above command appends to the existing line and potentially makes the file incorrect.

**Comment by deevus** [comment]
@nightroman You're probably right. @lukesampson what do you think?

**Comment by deevus** [comment]
I've reverted #355 so we can discuss since you make a good point

**Comment by deevus** [comment]
@nightroman I've talked it over with @lukesampson and we think the best option would be to document it only to avoid being intrusive. 

I was a little overzealous and for that I apologise :)

**Comment by deevus** [comment]
@nightroman @dre1080 [Can I Use Scoop In Bash?](/lukesampson/scoop/wiki/Can-I-Use-Scoop-In-Bash%3F)

**Comment by nightroman** [comment]
@deevus , thank you, I also think a wiki page is a good solution.

I would suggest to change the alias from

```
alias scoop="powershell scoop.ps1"
```

to

```
alias scoop="-noprofile -ex unrestricted scoop.ps1"
```

(like in *scoop.cmd*). At least `-noprofile` is the important bit. A user profile may contain something that may alter scoop work.

**Comment by deevus** [comment]
@nightroman I've updated the wiki page. Thanks!

**Comment by shoogle** [comment]
It's actually [better to use a function rather than an alias](https://askubuntu.com/a/98791):

```bash
function scoop() { powershell -ex unrestricted scoop.ps1 "$@" ;} && export -f scoop
```
Exported functions can be called from scripts whereas aliases are only defined in the current shell.

While editing the [Wiki page](https://github.com/lukesampson/scoop/wiki/Can-I-Use-Scoop-In-Bash%3F) I noticed that `-noprofile` had been [removed](https://github.com/lukesampson/scoop/wiki/Can-I-use-Scoop-in-bash%3F/_compare/eb10a13b06ed1cb2c264d8d83cbd81280307679c...43f8075de11e2bcb4127f29c7db13c5c0e838a04) from the command, though no reason was given. Perhaps @lukesampson found a situation where `-noprofile` has undesirable results?

**Comment by odahcam** [comment]
Hey, is this issue about running `scoop` itself in git bash or running scoop-installed programs in git bash?

**Comment by bboysnick5** [comment]
I just migrated to nushell. After executing scoop update *, it just printed a lot of errors at the end like following: 
ERROR '.Origin' isn't installed.
ERROR '.QtWebEngineProcess' isn't installed.
ERROR '.VirtualBox' isn't installed.
ERROR '.aws' isn't installed.
ERROR '.azure' isn't installed.
ERROR '.cache' isn't installed.
ERROR '.conda' isn't installed.
ERROR '.config' isn't installed.

Can anyone advise?

**Comment by shoogle** [comment]
@bboysnick5, that's a new problem so please open a new issue for it. You can cross-link to this issue if you think it's relevant.

**Comment by bboysnick5** [comment]
sure.
