### ISSUE TITLE
Don't say an application installed successfully if there were errors in its post install script.

### ISSUE THREAD

**Issue by vedantroy** [lukesampson/scoop#3554]
I installed youtube-dl. I also installed the suggested dependency vcredist2010.

When I run youtube-dl, I get the error "The code execution cannot proceed because MSVCR100.dll was not found. Reinstalling the program may fix this problem".

I am a bit confused as to why youtube-dl relies on a dll anyway, as far as I was aware, the command line version of youtube-dl has no such dependency.

**Edit**: Running `scoop install vcredist2010` gave the errors:

```
Running post-install script...
ERROR Exception calling "Start" with "0" argument(s): "The requested operation requires elevation"
ERROR Exception calling "Start" with "0" argument(s): "The requested operation requires elevation"
'vcredist2010' (10.0.40219) was installed successfully!
```

I fixed the problem by installing sudo with scoop and then running `sudo scoop install vcredist2010`. Afterwards, youtube-dl ran correctly.

I think if a post-install script fails, then scoop should probably not say that the item installed successfully.

**Comment by niheaven** [comment]
ref: https://github.com/ScoopInstaller/Main/issues/200

**Comment by kroppt** [comment]
I think one reason that post-install script failures aren't handled currently is because when an app fails, it would need to undo operations (deleting the new install) or perform the uninstall script, but that can be done by the user. Doing something else might just break stuff even more, depending on how the manifest is set up.

I do agree that it shouldn't _say_ that it was successful, which is the issue here.

The question is how to check if there was a failure. If the first line fails, but the second succeeds, how do we know? Perhaps a PowerShell function in scoop that can be called from the post-install scripts should be added, so bucket maintainers can prevent undefined behavior.

Additionally, if we tell the user that the install failed, but the app still shows up as installed under `scoop list`, then I think that would be contradiction. So, I think a better way to resolve this would be to tell the user, if we can check for errors in the script, that there were errors during the installation process, and let maintainers cancel the post-install if that happens, perhaps as a parameter for the function.

**Comment by domicioam** [comment]
This issue isn't fixed. Scoop still says the installation was successful when there is an error.
