### ISSUE TITLE
consider Dhall for manifests 

### ISSUE THREAD

**Issue by ghost** [lukesampson/scoop#3741]
consider Dhall for manifests for apps that work with scoop.

I read some of https://github.com/lukesampson/scoop/issues/2609, then stopped as it was pretty boring. 
regarding, [supporting yaml](https://github.com/Ash258/scoop/issues/2), I think it and python are weird choices as people don't expect whitespace to be significant. That particular feature adds cognitive load on users without any real benefits.

site for Dhall. https://dhall-lang.org/

features in Dhall that make it better than a general-purpose programming language.
see 'Turing-completeness is not a feature' on Dhall site for the most compelling feature if Turing complete language is undesired.

it looks better than reading python or yaml syntax as it doesn't have significant whitespace. also, I haven't heard of any hype about this unlike python, that's a nice sign.

also, official https://github.com/dhall-lang/dhall-lang/wiki/Cheatsheet, and the wiki looks better than a experimental project's wiki, in general. Its more fleshed out than the scoop wiki.

dhall tutorial https://learnxinyminutes.com/docs/dhall/ , not officially on dhall site.
----

regards ratatoeey

**Comment by ratatoeey** [comment]
this is mainly heuristics stuff, so far. I don't know whether it makes sense for scoop to move from json manifests.

But I plan on getting fluent in using Dhall before I say anything more. Its also better than json. Its only better because it learns form mistakes of others, so I hope it will get better.

----

regards ratatoeey
