### ISSUE TITLE
Can't install heroku-cli locally but can do it globally

### ISSUE THREAD

**Issue by ither** [lukesampson/scoop#3832]
Trying to install it locally bring the "WARN  Can not create symlink while running from un-elevated prompt. Installation is not affected" message but it just create the directory in the apps and nothing more. Doing it elevated also show the same behaviour but installing it globally with the -g flag, runs fine. I suspect that the compressed file confuse 7zip. 

Don't know if it deserves a patch, installing it globally works fine. Maybe a warning or a note or this already exists and I didn't see it ;-)

**Comment by Ash258** [comment]
Can reproduce halfway, but application could be used without any issue. 

Your windows user is administrator right?

There is pretty much possible something like this happen, since maintainers of heroku are boundling everything with it and node_modules folder contains symlinks, lots of symlinks.

![image](https://user-images.githubusercontent.com/13260377/73288823-fae30480-41fb-11ea-883a-e7f873eb214c.png)

**Comment by ither** [comment]
Yes, I have administrative rights and noticed the symlinks. Because of that I said that probably 7zip got confused. But anyway, thanks.
