### ISSUE TITLE
Cannot install signal: URL ...#/dl.7z is not valid, connection timed out, but fine with curl

### ISSUE THREAD

**Issue by dionysius** [lukesampson/scoop#3997]
```
> scoop install signal
Installing 'signal' (1.34.1) [64bit]
Timeout für Vorgang überschritten
URL https://updates.signal.org/desktop/signal-desktop-win-1.34.1.exe#/dl.7z is not valid
```

**Comment by StarsbySea** [comment]
SIGNAL software can be downloaded and installed properly with me, maybe you need to check your internet connection. Please use your browser or downloader to see if you can access the download file: `https://updates.signal.org/desktop/signal-desktop-win-1.34.1.exe`

flux, the cause of the error seems to be something wrong with their download server, and I was also unable to download properly (`https://justgetflux.com/flux-setup4-111.exe`). 

If you need to install this software now, you can open flux.json (usually located at this address: C:\Users\<your username>\scoop\buckets\extras\bucket\flux.json), change `https://justgetflux.com/flux-setup4-111.exe` to `https://justgetflux.com/flux-setup.exe`, then you can download and install flux with scoop.

Thank you for your feedback and look forward to your further response.

**Comment by dionysius** [comment]
Thank you for your help. Unfortunately it seems to be the related to the download mechanic of scoop. Your screenshot shows it loaded the .exe from your cache.

I tried with co-check with curl (I think I have it because of git), that's why I was thinking it's an issue with scoop.

```bash
C:\Users\Dionysius
λ scoop install signal
Installing 'signal' (1.34.1) [64bit]
Timeout für Vorgang überschritten
URL https://updates.signal.org/desktop/signal-desktop-win-1.34.1.exe#/dl.7z is not valid

C:\Users\Dionysius
λ curl https://updates.signal.org/desktop/signal-desktop-win-1.34.1.exe -o test.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  103M  100  103M    0     0   103M      0  0:00:01  0:00:01 --:--:-- 81.6M

C:\Users\Dionysius
λ sha512sum.exe test.exe
86fac022eedec2871e3507a255c7a777082dc27f79b0928e95da0f08024e3cacf7966d2235f8c54b170f9a22815f695715742ea1161b939c58976855ac9def97 *test.exe
```
and the hash matches https://github.com/lukesampson/scoop-extras/blob/master/bucket/signal.json#L7

**Comment by dionysius** [comment]
Unfortunately there seems to be no debug option for `install`, but there is a `-k`/`--no-cache` option. Can you install it with that set?

```bash
C:\Users\Dionysius
λ scoop help install
Usage: scoop install <app> [options]

e.g. The usual way to install an app (uses your local 'buckets'):
     scoop install git

To install an app from a manifest at a URL:
     scoop install https://raw.githubusercontent.com/ScoopInstaller/Main/master/bucket/runat.json

To install an app from a manifest on your computer
     scoop install \path\to\app.json

Options:
  -g, --global              Install the app globally
  -i, --independent         Don't install dependencies automatically
  -k, --no-cache            Don't use the download cache
  -s, --skip                Skip hash validation (use with caution!)
  -a, --arch <32bit|64bit>  Use the specified architecture, if the app supports it
```

**Comment by StarsbySea** [comment]
As you said, I just tried installing signal again and everything turned out fine. Although the first install prompted a timeout (my network wasn't very good), it installed correctly the second time around.
```
PS C:\Users\Kevin> scoop install signal --no-cache
Installing 'signal' (1.34.1) [64bit]
WARN  Cache is being ignored.
signal-desktop-win-1.34.1.exe (103.4 MB) [>                                                   ]   2%
The operation has timed out.
URL https://updates.signal.org/desktop/signal-desktop-win-1.34.1.exe#/dl.7z is not valid

PS C:\Users\Kevin> scoop uninstall signal
Uninstalling 'signal' ().
'signal' was uninstalled.

PS C:\Users\Kevin> scoop install signal --no-cache
Installing 'signal' (1.34.1) [64bit]
WARN  Cache is being ignored.
signal-desktop-win-1.34.1.exe (103.4 MB) [=======================] 100%
Checking hash of signal-desktop-win-1.34.1.exe ... ok.
Extracting dl.7z ... done.
Running pre-install script...
Linking ~\scoop\apps\signal\current => ~\scoop\apps\signal\1.34.1
Creating shim for 'signal'.
Creating shortcut for Signal (signal.exe)
'signal' (1.34.1) was installed successfully!
```
To rule out that it was my computer's specific environmental configuration, I opened the Windows sandbox and installed scoop and singal fresh, and everything turned out fine.
```
PS C:\Users\WDAGUtilityAccount> Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
Initializing...
Downloading scoop...
Extracting...
Creating shim...
Downloading main bucket...
Extracting...
Adding ~\scoop\shims to your path.
'lastupdate' has been set to '2020-05-30T21:58:39.5711657+08:00'
Scoop was installed successfully!
Type 'scoop help' for instructions.

PS C:\Users\WDAGUtilityAccount> scoop install git
Installing '7zip' (19.00) [64bit]
7z1900-x64.msi (1.7 MB) [=====================================================================================] 100%
Checking hash of 7z1900-x64.msi ... ok.
Extracting 7z1900-x64.msi ... done.
Linking ~\scoop\apps\7zip\current => ~\scoop\apps\7zip\19.00
Creating shim for '7z'.
Creating shortcut for 7-Zip (7zFM.exe)
'7zip' (19.00) was installed successfully!
Installing 'git' (2.26.2.windows.1) [64bit]
PortableGit-2.26.2-64-bit.7z.exe (41.1 MB) [==================================================================] 100%
Checking hash of PortableGit-2.26.2-64-bit.7z.exe ... ok.
Extracting dl.7z ... done.
Linking ~\scoop\apps\git\current => ~\scoop\apps\git\2.26.2.windows.1
Creating shim for 'git'.
Creating shim for 'gitk'.
Creating shim for 'git-gui'.
Creating shim for 'tig'.
Creating shim for 'git-bash'.
Creating shortcut for Git Bash (git-bash.exe)
Creating shortcut for Git GUI (git-gui.exe)
Running post-install script...
'git' (2.26.2.windows.1) was installed successfully!

PS C:\Users\WDAGUtilityAccount> scoop bucket add extras
Checking repo... ok
The extras bucket was added successfully.

PS C:\Users\WDAGUtilityAccount> scoop install signal --no-cache
Installing 'signal' (1.34.1) [64bit]
WARN  Cache is being ignored.
signal-desktop-win-1.34.1.exe (103.4 MB) [=======================] 100%
Checking hash of signal-desktop-win-1.34.1.exe ... ok.
Extracting dl.7z ... done.
Running pre-install script...
Linking ~\scoop\apps\signal\current => ~\scoop\apps\signal\1.34.1
Creating shim for 'signal'.
Creating shortcut for Signal (signal.exe)
'signal' (1.34.1) was installed successfully!
```
Also, I found out that the terminal emulator you are using is Cmder, so I installed it as well, but using it to install signal is also normal.

Since I see your terminal output "Timeout für Vorgang überschritten", I'm guessing that there may be a small problem with your scoop configuration or system (network) configuration.
(Note: whatever the downloading error, scoop will output `URL https://<actual URL>#/dl.7z is not valid`, so it is not very helpful)

I will list below some of the operations that may help solve the problem, please try them out.
(can be done in order, after each one please try to see if you can install Signal)

1. Make the scoop directly connect to the Internet and please turn off the proxy server in the settings
`scoop config proxy none`

2. Install aria2 and let scoop download software through it
`scoop config proxy none`

3. Re-install scoop
(Follow the tutorial on the web to be sure to keep your data safe)

4. Use the "Network reset" function on Windows
(Be careful, it's in Settings - Network and Internet - Status - Network reset (at the bottom))

If none of the above works, then you may have to reinstall the system...

However, if you don't mind the hassle, you can manually download the Signal installer, rename it, and put it in scoop's cache folder so that scoop will call the cache install, which counts as one way.
You can open `C:\Users\<Username>\scoop\cache\signal.txt`, the first line is the download address, the content after `out=` is the file name specified by scoop.

I'm sorry, I can't reproduce the problem you have. I can't think of much else to do other than the above. If you are free, perhaps you can contact the developer and see what he can do.

Also I looked at the code in scoop that was responsible for the download, and since he was using a downloader that came with the system's own .net library, and I'm not very familiar with PowerShell (and C#) programming, there's not much I can do to help. Maybe a run of the System File Checker tool to repair missing or corrupted system files will help.
[Use the System File Checker tool to repair missing or corrupted system files](https://support.microsoft.com/help/929833/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system)

Looking forward to your further feedback.

**Comment by StarsbySea** [comment]
> Unfortunately there seems to be no debug option for install.

Actually what you're showing is already a debug log, but maybe we need a "line by line" debug log or some other more detailed log.

**Comment by dionysius** [comment]
Thank you very much for this long answer. I think we can't do much unless we have more options to track down the issue.

```
C:\Users\Dionysius
λ scoop config proxy
'proxy' is not set
```

The terminal doesn't matter, I get the same in plain windows powerscript (and same with [Microsoft Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701))

I'm not going to reinstall the system, but I'm looking forward to provide more info once scoop can print more debug output or someone can guide me what to look out for. I've a lot of software installed with scoop, so generally it's working totally finde, and it's just signal so far. (And I don't have the issue with curl, browsers, etc.)

```
C:\Users\Dionysius
λ scoop list
Installed apps:

  7zip 19.00
  adb 30.0.0
  android-sdk 4333796 [extras]
  blender 2.82a [extras]
  cacert 2020-01-01
  ccleaner 5.66.7716 [extras]
  cmder 1.3.14
  curl 7.70.0
  dark 3.11.2
  dbeaver 7.0.5 [extras]
  git 2.26.2.windows.1
  gitextensions 3.3.1 [extras]
  git-lfs 2.11.0
  go 1.14.3
  graphviz 2.38
  handbrake 1.3.2 [extras]
  imageglass 7.6.4.30 [extras]
  inkscape 1.0 [extras]
  innounp 0.49
  jq 1.6
  keepass 2.45 [extras]
  launchy 2.10.79 [extras]
  lessmsi 1.6.91
  lightscreen 2.4 [extras]
  mariadb 10.4.13
  meld 3.20.2 [extras]
  obs-studio 25.0.8 [extras]
  openjdk12 12.0.2-10 [java]
  openshot 2.5.1 [extras]
  paint.net 4.2.11 [extras]
  python 3.8.3
  signal  *failed*
  sudo 0.2020.01.26
  sumatrapdf 3.2 [extras]
  teamviewer 15.6.7 [extras]
  telegram 2.1.6 [extras]
  vlc 3.0.10 [extras]
  vscode 1.45.1 [extras]
  whatsapp 2.2019.8 [extras]
  windirstat 1.1.2 [extras]
  wireshark 3.2.4 [extras]
```

I don't mind not beeing able to install signal and as you pointed out there are some workarounds or just the normal install. But I still like to help to make scoop better by finding issues like that and thus I posted this issue here - maybe some day there'll be some advice from the developer. Right now I'm in the blank since I can't find a way to help out more to find the issue.

**Comment by dionysius** [comment]
I found out the issue, and this definitely needs more output in scoop and also a retry. I've found out my IPv6 is not working correctly (to my provider).

The DNS probably resolved to the IPv6 address of the signal server:
```
C:\Users\Dionysius
λ nslookup updates.signal.org
Server:  fritz.box
Address:  fd00::3a10:d5ff:fe5b:d19a

Nicht autorisierende Antwort:
Name:    d1ugeilqty6idm.cloudfront.net
Addresses:  2600:9000:2047:8800:16:675e:2280:93a1
          2600:9000:2047:5a00:16:675e:2280:93a1
          2600:9000:2047:800:16:675e:2280:93a1
          2600:9000:2047:9600:16:675e:2280:93a1
          2600:9000:2047:4a00:16:675e:2280:93a1
          2600:9000:2047:d400:16:675e:2280:93a1
          2600:9000:2047:3200:16:675e:2280:93a1
          2600:9000:2047:a000:16:675e:2280:93a1
          52.222.149.119
          52.222.149.158
          52.222.149.47
          52.222.149.3
Aliases:  updates.signal.org
```

When doing a `curl` with explicit `-6` (for ipv6) I get this connection timeout.
