### ISSUE TITLE
nomacs install failed

### ISSUE THREAD

**Issue by graphixillusion** [lukesampson/scoop#4065]
```
Could not find 'bin'! (error 16)
In C:\Users\User\scoop\apps\scoop\current\lib\core.ps1:510 car:9
+         throw "Could not find '$(fname $from)'! (error $($proc.ExitCo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find 'bin'! (error 16):String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find 'bin'! (error 16)
```
This happens with the last version (just released): 3.16.224

**Comment by gabrielrota** [comment]
Waiting fix I have reverted to previus
scoop install nomacs@3.14.2

**Comment by gabrielrota** [comment]
I fixing localy C:\Users\grota\scoop\buckets\extras\bucket\nomacs.json
from
"extract_dir": "nomacs-3.16.224\\bin",
to
"extract_dir": "nomacs-3.16.1709",

**Comment by rasa** [comment]
Closing as this issue is stale. Please reopen if this is still an issue.

**Comment by hgkamath** [comment]
Similar issue happened to me with package qrscan. The message that clued me to find this issue is the error message "Could not find", despite having downloaded and extracted zip file.

sorry for appending to this issue.

Once it is determined that it is a manifest typo, may I suggest that bug be filed as 
summary: ```json bucket manifest typo for <package>```
under respective github bucket project repository such as ```ScoopInstaller/Extras```

ex: filed my bug as "https://github.com/ScoopInstaller/Extras/issues/9321"
