### ISSUE TITLE
can't shim : file doesn't exist

### ISSUE THREAD

**Issue by nishanthkarthik** [lukesampson/scoop#416]
This is my manifest,

    {
        "homepage": "https://github.com/nishanthkarthik/netaccess-infiauth",
        "license": "https://raw.githubusercontent.com/nishanthkarthik/netaccess-infiauth/master/LICENSE",
        "version": "1.0.1",
        "architecture": 
        {
            "32bit|64bit": 
            {
                "url": "https://github.com/nishanthkarthik/netaccess-infiauth/releases/download/v1.0.1/Release.zip",
                "hash": "AD25FD7C903566893E1A39C400E92DBFD77F580910EBE078C9F5388961DFDD42"
            }
        },
        "extract_dir": "netaccess-auth",
        "bin": "netaccess.exe"
    }

I get file doesnt exist error, even though the netaccess.exe exists within the folder. Please help me out :)

**Comment by lukesampson** [comment]
You don't need the `architecture` stuff if it's the same for both, just put `url` and `hash` at the top level. Also `extract_dir` is a directory inside the .zip that you want to extract (rather than extracting everything from the zip). I don't think `netaccess-auth` is a directory inside the .zip, so you can just leave that out.

This should work:

```json
{
    "homepage": "https://github.com/nishanthkarthik/netaccess-infiauth",
    "license": "https://raw.githubusercontent.com/nishanthkarthik/netaccess-infiauth/master/LICENSE",
    "version": "1.0.1",
    "url": "https://github.com/nishanthkarthik/netaccess-infiauth/releases/download/v1.0.1/Release.zip",
    "hash": "AD25FD7C903566893E1A39C400E92DBFD77F580910EBE078C9F5388961DFDD42",
    "bin": "netaccess.exe"
}
```

**Comment by nishanthkarthik** [comment]
Brilliant! Thanks.
