### ISSUE TITLE
There is no shim for pip after `scoop install python`. Only a shim for python.exe

### ISSUE THREAD

**Issue by Boscop** [lukesampson/scoop#4167]
There is no shim for pip after `scoop install python`. Only a shim for python.exe, python3.exe and pythonw.exe.
But pip.exe exists in `C:\Users\me\scoop\apps\python\current\Scripts`.
How can I tell scoop to also create a shim for pip?

**Comment by 0x326** [comment]
(This issue should be posted at the https://github.com/ScoopInstaller/Main repo since it concerns a package manifest)

Looking at the [package manifest](https://github.com/ScoopInstaller/Main/blob/master/bucket/python.json), it seems like `Scripts` is put in your PATH variable. Can you verify whether that is or isn't the case?
