### ISSUE TITLE
Failed to create start menu shortcut for GUI application

### ISSUE THREAD

**Issue by finalwhy** [lukesampson/scoop#4246]
When I want to install a GUI application by the scoop (for example typora or everything), scoop able to successfully install the application, but can not create a shortcut to the Start menu. The output of scoop is as follows
![Flicker_List_Zpla0gYInW](https://user-images.githubusercontent.com/24859256/106361375-93085200-6358-11eb-8be4-f8cac7057be4.png)

![msedge_fnBa2WKT9x](https://user-images.githubusercontent.com/24859256/106361380-969bd900-6358-11eb-9e84-0a44f100f1c5.png)
(All shortcuts in the "Scoop Apps" folder are created by myself, including this folder)

**Comment by HUMORCE** [comment]
search `everything.lnk` in Everything, any result?

**Comment by finalwhy** [comment]
> search `everything.lnk` in Everything, any result?

no，there is no any `.lnk` file in everything
![explorer_RXBxB8hofY](https://user-images.githubusercontent.com/24859256/106362076-ddd79900-635b-11eb-9542-fef728b3a542.png)

**Comment by HUMORCE** [comment]
I mean use app Everything to search everything.lnk

![screenshot_20210130172203](https://user-images.githubusercontent.com/4353480/106363321-b236bd80-631f-11eb-9dbb-9f21be22310c.png)

**Comment by finalwhy** [comment]
> I mean use app Everything to search everything.lnk
> 
> ![screenshot_20210130172203](https://user-images.githubusercontent.com/4353480/106363321-b236bd80-631f-11eb-9dbb-9f21be22310c.png)

Everthing: uninstall and then install ,nothing
![everything](https://user-images.githubusercontent.com/24859256/106363873-298f4000-6366-11eb-82ce-90732072323b.png)

Quicklook: new installed，nothing too
![quicklook](https://user-images.githubusercontent.com/24859256/106363898-44fa4b00-6366-11eb-8a24-8ce760299414.png)

**Comment by HUMORCE** [comment]
remove `Scoop Apps` folder you created,
run windows powershell (C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe)
exec `scoop reset *`

scoop can also install pwsh core, but I think there are some problems with the current configuration of the manifest.

other ways to install powershell core:
https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-7.1

I installed pwsh core by dotNet global tool.

If you have joined the windows insider program: https://github.com/lukesampson/scoop/issues/3941

**Comment by ssfjhh** [comment]
After I reinstall the Windows system. First, I install pwsh and Windows Terminal then run this command in it to install scoop.
`iwr -useb get.scoop.sh | iex`

I found all the shortcut are created in the pwsh folder rather than "%HomePath%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps". The folder also ends with "AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps", this led me to come up with the solution.

I guess scoop was limited to create this folder "%HomePath%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps".

So I uninstall Windows Terminal and pwsh just run `scoop reset *` in Powershell. then PowerShell tells me that "scripts cannot run on this computer." Then I run this command `Set-ExecutionPolicy RemoteSigned` to remove this limit. Then, run "scoop reset *"
 again. The problem was solved perfectly.

Shortly speaking. To solve this problem, follow these 3 steps.
1. Uninstall Windows Terminal and pwsh. ( I'm not sure if it's necessary, you can have a try.)
2. Run `Set-ExecutionPolicy RemoteSigned` in Powershell.
3. Run `scoop reset *` in Powershell.
4. Reinstall Windows Terminal and pwsh as you wash.

**Comment by finalwhy** [comment]
> After I reinstall the Windows system. First, I install pwsh and Windows Terminal then run this command in it to install scoop.
> `iwr -useb get.scoop.sh | iex`
> 
> I found all the shortcut are created in the pwsh folder rather than "%HomePath%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps". The folder also ends with "AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps", this led me to come up with the solution.
> 
> I guess scoop was limited to create this folder "%HomePath%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps".
> 
> So I uninstall Windows Terminal and pwsh just run `scoop reset *` in Powershell. then PowerShell tells me that "scripts cannot run on this computer." Then I run this command `Set-ExecutionPolicy RemoteSigned` to remove this limit. Then, run "scoop reset *"
> again. The problem was solved perfectly.
> 
> Shortly speaking. To solve this problem, follow these 3 steps.
> 
> 1. Uninstall Windows Terminal and pwsh. ( I'm not sure if it's necessary, you can have a try.)
> 2. Run `Set-ExecutionPolicy RemoteSigned` in Powershell.
> 3. Run `scoop reset *` in Powershell.
> 4. Reinstall Windows Terminal and pwsh as you wash.

Thanks, I have solved this problem by using the `.msi` file to reinstall powershell (previously my powershell core was installed through the Microsoft Store). I think the cause of the problem may be some kind of sandbox mechanism in the Microsoft Store. When the powershell installed through the Microsoft Store executes the script, `~` is not pointing to the current user's folder, but to a temporary user folder inside it
