### ISSUE TITLE
How to specify the installation of 32-bit software on a 64-bit system

### ISSUE THREAD

**Issue by DoveBoy** [lukesampson/scoop#4329]
My Windows system is `64-bit`, usually the default installation via `scoop install` command follows the system `64-bit` programs, but I need to install `32-bit` programs, what **parameters** do I need to add to the `scoop install` command?
After installing [officetoolplus](https://raw.githubusercontent.com/chawyehsu/dorado/master/bucket/officetoolplus.json), you need to install [dotnet-desktop-runtime](https://raw.githubusercontent.com/chawyehsu/dorado/master/bucket/dotnet-desktop-runtime.json) at the same time to start properly, but `64-bit` `dotnet` installed by `scoop install` cannot start, only `32-bit` `dotnet` can start properly

**Comment by HUMORCE** [comment]
if x64 version is not required with you:
```
scoop install dotnet-desktop-runtime -a 32bit
```

for installing the dotnet desktop runtime x86 and x64, suggested using the [official installer](https://dotnet.microsoft.com/download/dotnet) or [visual studio](https://visualstudio.microsoft.com/).

if you must install them via scoop:
you need to customize the manifest, otherwise, you can only install one of them. (x86 or x64)

e.g.
```
{ cd to path of dotnet-desktop-runtime.json }
cp dotnet-desktop-runtime.json dotnet-desktop-runtime-x86.json
scoop install dotnet-desktop-runtime-x86 -a 32bit
scoop install dotnet-desktop-runtime
```
this is not the best solution, but does not require any modifications of the manifest.

**Comment by DoveBoy** [comment]
@HUMORCE How to install both `32-bit` and `64-bit` `dotnet-desktop-runtime` with `scoop install`, while `scoop update *` can always automatically upgrade `32-bit` and `64-bit` `dotnet-desktop-runtime`?

**Comment by HUMORCE** [comment]
clearly in the previous comment.

**Comment by DoveBoy** [comment]
@HUMORCE Thank you
