### ISSUE TITLE
Scoop on an External Drive

### ISSUE THREAD

**Issue by AbhayAysola** [lukesampson/scoop#4343]
I'm trying to install Scoop onto an External Drive and followed the extra installation steps.
```
$env:SCOOP='D:\Applications\Scoop'
[Environment]::SetEnvironmentVariable('SCOOP', $env:SCOOP, 'User')
# run the installer
```

```
$env:SCOOP_GLOBAL='F:\GlobalScoopApps'
[Environment]::SetEnvironmentVariable('SCOOP_GLOBAL', $env:SCOOP_GLOBAL, 'Machine')
# run the installer
```
This works fine, but everytime I try installing a program I get a similar error 
```
PS D:\> scoop install curl
Installing '7zip' (19.00) [64bit]
7z1900-x64.msi (1.7 MB) [===================================================================] 100%
Checking hash of 7z1900-x64.msi ... ok.
Extracting 7z1900-x64.msi ... done.
Linking D:\Scoop\apps\7zip\current => D:\Scoop\apps\7zip\19.00
Local NTFS volumes are required to complete the operation.
Creating shim for '7z'.
Can't shim '7z.exe': File doesn't exist.
```

**Comment by TheInterestingSoul** [comment]
Same issue. Maybe I'll try [PortableApps](https://portableapps.com/).

**Comment by AbhayAysola** [comment]
Yeah I'll probably do the same.

**Comment by AbhayAysola** [comment]
Couldn't find scoop on PortableApps though

**Comment by TheInterestingSoul** [comment]
well, I retried Scoop and found several conclusions,
- Scoop **has the ability to install softwares to a flash drive**;
- However, If you want to install Scoop itself to a flash drive, then you need do a lot of config work (change absolute path to relative path, etc.), since Scoop is designed for a local disk.

My solution is to create shortcuts, follow these steps:
1. As for me, i decide to install Scoop to my local disk, and softwares to my external drive (E:\), so the first thing is to configure the environment variable:
```powershell
$env:SCOOP='D:\scoop'
[environment]::setEnvironmentVariable('SCOOP',$env:SCOOP,'User')
iwr -useb get.scoop.sh | iex # reinstall Scoop

$env:SCOOP_GLOBAL='E:\Applications'
[environment]::setEnvironmentVariable('SCOOP_GLOBAL',$env:SCOOP_GLOBAL,'Machine')
```
You can also set them in Control Panel.
![control panel](https://user-images.githubusercontent.com/41455159/116772977-3581bf80-aa85-11eb-9715-0bfe637eee0a.png)

2. Install software with `--global` option:
```powershell
scoop install notepadplusplus -g
```
Just ignore the shim error.

3. We are going to create shortcuts that use relative path rathen than absolute path. Go to your flash drive location and find `Applicatons\apps\notepadplusplus\7.9.5`, right click on `notepad++.exe` and select `create shortcut`
![create shortcuts](https://user-images.githubusercontent.com/41455159/116773180-7d551680-aa86-11eb-8c36-3a94620a5538.png)

Note that the newly created shortcut is different from the original program.
![diff](https://user-images.githubusercontent.com/41455159/116773260-08361100-aa87-11eb-83f5-c2bc08073f1c.png)

4. Move it to the root dir of the drive (or anywhere you like). Right click on the shortcut and click `Properties`. Fill the `target` label with these string:
```
%WINDIR%\System32\cmd.exe /c start Applications\apps\notepadplusplus\7.9.5\notepad++.exe
```
`%WINDIR%` refers to `C:\Windows` if Windows is in C drive
`/C` means close cmd terminal immediately after `start` command.
![Properties](https://user-images.githubusercontent.com/41455159/116773387-b2159d80-aa87-11eb-98b9-014311239277.png)
You can also change the icon that the shortcut uses.

That's it. Double click on it and check if it works.

**Comment by AbhayAysola** [comment]
Thanks for the guide but I changed my mind and installed it the normal way so it's all good
