### ISSUE TITLE
7zip

### ISSUE THREAD

**Issue by Stanzilla** [lukesampson/scoop#511]
Since you seem to be using the beta version of 7zip in scoop, the up to date version is 15.07:

http://www.7-zip.org/a/7z1507.exe
http://www.7-zip.org/a/7z1507-x64.exe

**Comment by deevus** [comment]
The new version uses a self extracting installer IIRC whereas the version in scoop is an msi. 

I actually looked at this and from memory I couldn't get it to extract to a directory without admin rights, which poses a problem since scoop is supposed to be able to function without it. 

If you have 7z installed already you can unzip it, however this presents a chicken and egg problem: if you are installing scoop and you don't have 7z, you can't unzip the self extracting installer without admin rights.

**Comment by Stanzilla** [comment]
https://sourceforge.net/p/sevenzip/discussion/45797/thread/7d9ac43f/#b9c4/b9da/ade1

MSI installers might come back

**Comment by Stanzilla** [comment]
MSI installers are back: http://www.7-zip.org/download.html

**Comment by Stanzilla** [comment]
https://github.com/lukesampson/scoop/pull/550
