### ISSUE TITLE
PATH length

### ISSUE THREAD

**Issue by thejustinwalsh** [lukesampson/scoop#551]
On WIndows 7 (x64) scoop is adding a new entry to my path for gcc, python, ruby and maybe a few others and this blows my path out beyond the 2048 character limit and things start to break.

Any suggestions to fix this? Does it have to rely on the PATH variable to work?

**Comment by lukesampson** [comment]
The only thing I can think of is to install scoop to a shorter path, like C:\scoop by setting the $env:SCOOP variable (see #249), and then reinstalling everything.

Not ideal, I know. Scoop tries to avoid this by using shims instead of adding everything to your path, but then a lot of programs need to add directories to your path anyway.

**Comment by thejustinwalsh** [comment]
I'll try the shorter path. Thanks!
