### ISSUE TITLE
Not handling special characters in path

### ISSUE THREAD

**Issue by rapito** [lukesampson/scoop#572]
Scoop throws an exception if it founds any special characters in it's execution path.

- OS: ```Windows 10```
- Username: ```Robert Adrián``` 
- Error:

>
``` 
& : The term 'C:\Users\RobertAdri
n\appdata\local\scoop\apps\scoop\current\bin\scoop.ps1' is not recognized as
the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is
correct and try again.
At C:\Users\RobertAdrián\appdata\local\scoop\shims\scoop.ps1:5 char:70
+ ... ion.expectingInput) { $input | & $path @args } else { & $path @args }
+                                                             ~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Robert...t\bin\scoop.p
   s1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by deevus** [comment]
@rivy Any chance of a PR with those fixes?

**Comment by rivy** [comment]
I have a change set that "works on my machine" (https://github.com/rivy/scoop/commit/e69c922901e12e3a65a89a8d6acab1edb14f6294), meaning I added an user named "tëst" and it all works. I'll need someone who uses a machine with an international character set to try it before I can be more sure of the fix.

I believe I have the it will be the fix for all #507 and #572. I likely have the fix for #603 as well (not in the commit chain yet).

I've got a test branch that I'm working on that should be pull-and-play for someone else to try (it's the 't-fix' branch). But I want to polish it a bit before I give out the install instructions. Maybe over the weekend...

**Comment by rivy** [comment]
@rapito I have a possible fix up-and-running in my fork ([rivy/scoop](https://github.com/rivy/scoop)). But it still needs testing, especially for international use. Give it a try if you have time...

For installation, use:

##### CMD Shell &middot; `C:\>`

    powershell -command "iex (new-object net.webclient).downloadstring( 'https://raw.github.com/rivy/scoop/master/bin/install.ps1' )"
    set PATH=%PATH%;%LOCALAPPDATA%\scoop\shims

##### PowerShell &middot; `PS C:\>`

    iex (new-object net.webclient).downloadstring( 'https://raw.github.com/rivy/scoop/master/bin/install.ps1' )

`scoop` should then just work, no restart required.

If you later wish to delete the fork, use `cmd /c "rmdir /s /q ""%LOCALAPPDATA%\scoop"" "`. Note that if you delete the fork, you will also delete all content which was locally installed by `scoop` (although it's easily replaced by re-installation via `scoop` again).

**Comment by rapito** [comment]
@rivy, just tested your fork and I could install successfully the following packages:

- curl
- 7zip
- innounp

So it seems it's now working ok :dancer: 

As a side node (possibly a new issue): Couldn't install openssl because of a 404 on the server, seems like that package/bucket must be updated.

**Comment by rivy** [comment]
@rapito, In order to keep a cleaner development line, I've been avoiding pulling in commits which are purely bucket updates. So, the default bucket hadn't been updated in a while...

However, I just updated it in 'master'. A `scoop update` should pull everything (or a reinstall if you've removed it already). You should be able to test now with all the latest manifests.

If you run into any issues, please let me know.

**Comment by lool** [comment]
Hi,
Had to uninstall scoop before testing this:
iex (new-object net.webclient).downloadstring( 'https://raw.github.com/rivy/scoop/master/bin/install.ps1' )

It seems to work better in that it can unpack lzma stuff without barking at 7z.exe not being found under my user, however it fails with "can't shim xyz.exe" errors:

> creating shim for git
> can't shim cmd\git.exe: file doesn't exist

This might be because the scoop apps moved forward when this binary didn't.

Would you mind updating the test binary?

Thanks,

**Comment by damnhandy** [comment]
@lool when you get the can't shim error, does it skip right to `can't shim`, or do you also see the lines where it states that it's downloading, checking the hash, etc.? Just curious if you're having a similar issue to #774 ?

**Comment by lool** [comment]
This is how scoop install git fails after a fresh install when using the official release:
[...]
downloading http://www.7-zip.org/a/7z1514-x64.msi...done
checking hash...ok
extracting...done
creating shim for 7z
7zip (15.14) was installed successfully!
installing git (2.8.0.windows.1)
downloading https://github.com/git-for-windows/git/releases/download/v2.8.0.wind
ows.1/PortableGit-2.8.0-64-bit.7z.exe#/dl.7z...done
checking hash...ok
extracting...& : Le terme «C:\Users\Lo<c Minier\AppData\Local\scoop\apps\7zip\15
.14\7z.exe»
n'est pas reconnu comme nom d'applet de commande, fonction, fichier de script
ou programme exécutable. Vérifiez l'orthographe du nom, ou si un chemin
d'accès existe, vérifiez que le chemin d'accès est correct et réessayez.
Au caractère C:\Users\Loïc Minier\appdata\local\scoop\shims\7z.ps1:5 : 70
+ if($myinvocation.expectingInput) { $input | & $path @args } else { & $path
@args ...
+                                                                      ~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Lo<c M...ip\15.14\7z.e
   xe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

exit code was 3

C:\Users\Loïc Minier>

**Comment by damnhandy** [comment]
Well, looks like we have different issues then. In my case, it's completely skipping over the 7zip installation and I have no feedback on the git download and hash verification. So, likely another issue. :(

**Comment by lukesampson** [comment]
I've tested with "Robert Adrián" and "Loïc Minier" as usernames, seems to work.
