### ISSUE TITLE
command prompt doesn't always start on a newline

### ISSUE THREAD

**Issue by H3Chief** [lukesampson/scoop#593]
I am experiencing an issue where I use a tool like `curl` to send something to `stdout`, and then the command prompt shows up on the same line as the output.  For example, 

I hit the github api example 3 consecutive times, and here's what my shell looked like:

```bash
curl https://api.github.com/zen
Anything added dilutes everything else.~ $ curl https://api.github.com/zen
Design for failure.~ $ curl https://api.github.com/zen
Speak like a human.~ $
```

Instead of:

```bash
curl https://api.github.com/zen
Anything added dilutes everything else.
~ $ curl https://api.github.com/zen
Design for failure.
~ $ curl https://api.github.com/zen
Speak like a human.
~ $
```

**Comment by Cyianor** [comment]
I can reproduce this, but this isn't an issue related to scoop. The problem is that `curl https://api.github.com/zen` doesn't seem to send a new line at the end. That's why the command prompt appears on the same line as the output.

It's the same with any other page. Just try `curl https://www.google.se` for example. (for the `.com` version it actually works that the command prompt is on a new line. Guess that's due to the pages source code having an empty line at the end.
