### ISSUE TITLE
Upgrade to JDK 8

### ISSUE THREAD

**Issue by mathieucarbou** [lukesampson/scoop#633]
openjdk.json is set to Java 7. Now Java 8 is there since a while.
which scoop command could I run to install the Java 8 version ? Is there a way to easily modify or update locally the config files ?
Thanks!

**Comment by saildata** [comment]
@mathieucarbou if you're wanting OpenJDK, then you can create the app manifest described in the **[wiki](https://github.com/lukesampson/scoop/wiki/App-Manifests)** and issue a pull request. It's a really simple JSON file format - the wiki page has an example or just copy one out of the *apps* folder in your scoop directory and use that as a template. 

If you want to go with the alternative, you can grab *oraclejdk (1.8.0-u60)* from the **[extras bucket](https://github.com/lukesampson/scoop-extras)**.

**Comment by scottwillmoore** [comment]
Thank you @saildata, currently we are using the [openjdk-unofficial-builds](https://github.com/alexkasko/openjdk-unofficial-builds), however these have not been updated to [support JDK 8](https://github.com/alexkasko/openjdk-unofficial-builds/issues/17), and it looks as if this may not happen for quite a while.

I just saw that someone mentioned that [Zulu](http://zulu.org/download/) create JDK 8 builds, in the [openjdk-unofficial-builds](https://github.com/alexkasko/openjdk-unofficial-builds) issues page. The developer of the unofficial build mentions that this may be more similar to Oracle JDK 8, than OpenJDK 8, but from my point of view it looks pretty good.

> Zulu is a certified build of OpenJDK that is fully compliant with the Java SE standard. Zulu is 100% open source and freely downloadable.

I would update the manifest myself, but I have moved to Linux for the past six months, and do not have any Windows machines to test it on. Luckily it should be a pretty trivial update, but if we use the Zulu build of the OpenJDK, should we rename the package, or add an extra note so that it is obvious to people that it is not a pure OpenJDK build.

**Comment by saildata** [comment]
Awesome. I'm also a Linux native, and have used scoop for a while now since I multiboot for work.. I'm glad y'all are using OpenJDK, but wanted to provide the alternative if you were able to use either environment.

**Comment by damnhandy** [comment]
@scottwillmoore I've taken a look at using Azul's Zulu and it's going to take some shenanigans in order to get it work with Scoop. Azul is forbidding direct downloads to the link http://cdn.azulsystems.com/zulu/bin/zulu1.8.0_66-8.11.0.1-win64.zip unless the referrer is http://www.azul.com/downloads/zulu/zulu-windows/ But it also seems that the Referer header is also not enough as they seem to doing additional checks when the download link is clicked. This is all making the hassles of downloading Oracle's JDK much easier.

**Comment by scottwillmoore** [comment]
That complicates things! After a quick Google search I was able to find [this](https://support.azulsystems.com/hc/communities/public/questions/202463190-Provide-proper-links-to-Linux-binaries) post on their support forums. So apparently it is possible to do using metadata in the HTTP request.

Scoop does not currently support adding a referrer to the HTTP request, however in the past I added support for embdedding cookies into the HTTP request. You can see on [this](https://github.com/lukesampson/scoop/blob/0ee16c2e0478edb3b4647b57137566f078f69198/lib/install.ps1#L115) line how it is done,and in my [pull request](https://github.com/lukesampson/scoop/commit/0af8ebff5be43aaabafe53e64e789c9245871aba) what other code I modified to make it work.

You could either implement support for including a referrer in the request, using the current syntax.

````json
{
    "cookie": "COOKIE-NAME",
    "referrer": "REFERRAL-URL"
}
````

However we are currently hacking (hard coding) in modifications for every HTTP request metadata that we need to use (which currently is only Cookies, and Referrers, but may be more in the future). So maybe the syntax would be better like so. Which dynamically includes the http metadata which is found in the key-value list supplied (rather than the current method which hard codes these values into the specification). A downside to this approach is that it would break a very small number of manifests which already exist, which will need to be updated. The [OracleJDK](https://github.com/lukesampson/scoop-extras/blob/master/oraclejdk.json) manifests are the only ones I know which require this feature.

````json
{
    "request": {
        "Cookie": "COOKIE-NAME",
        "Referrer": "REFERRAL-URL"
    }
}
````

We should check what @lukesampson thinks about these changes.

If you implement these features please remeber to update the [wiki](https://github.com/lukesampson/scoop/wiki/App-Manifests) page which documents what can be used in app manifests.

I apologise, I should be doing this myself, but as mentioned above I currently do use Windows anymore. Good luck.

**Comment by lukesampson** [comment]
Thanks guys. If anyone wants to submit a PR to include the referrer for HTTP requests then I'd be happy to merge it. The first syntax @scottwillmoore shows above is better I think—nicer to read and type, and doesn't break anything.

**Comment by damnhandy** [comment]
But wouldn't it be great if getting a binary for a JDK didn't involve these sorts of shenanigans? I'll give this a look in the next week or two. At the moment, my teams are fine with the Oracle JDK, but Azul's Zulu is a nice option. It's a a shame that it has the same hoops to jump through as the Oracle JDK.

**Comment by martinlindhe** [comment]
The repo pointed to by openjdk.json [1] says "Project discontinued

This project is discontinued.

Up-to-date OpenJDK 8 binaries for Windows x86_64 are available in ojdkbuild [2] GitHub project."

However, the suggested repo ojdkbuild/ojdkbuild only provides x86_64 binaries.
Would a patch to change the formula for this be welcome, or should it maybe be a separate formula, or live in the scoopinstaller/versions ?

1: https://github.com/alexkasko/openjdk-unofficial-builds
2: https://github.com/ojdkbuild/ojdkbuild

**Comment by lukesampson** [comment]
I think leave openjdk.json using the current version since it supports x86 as well, but it probably would be useful to add a new manifest to the scoopinstaller/versions pointing to the ojdkbuild build. If ojdkbuild supports x86 at some point it can replace the main openjdk.

Lots of apps have a dependency on openjdk so we should replace that with oraclejdk, because it's probably what everyone uses anyway. I think it would be good to move oraclejdk to the main bucket, and remove the open-source requirement for the main bucket.

**Comment by martinlindhe** [comment]
>  I think it would be good to move oraclejdk to the main bucket, and remove the open-source requirement for the main bucket. 

I agree, especially given the pre-compiled nature of the buckets.

**Comment by martinlindhe** [comment]
@lukesampson so would patches moving oraclejdk.json from lukesampson/extras into lukesampson/scoop be accepted, or would it be better to hold this off, and have some proper discussion/vote about" remove the open-source requirement for the main bucket" first?

**Comment by lukesampson** [comment]
@scottwillmoore @saildata @damnhandy do you have any objections to making Oracle JDK the "default" JDK, instead of Open JDK? Moving Oracle JDK from extras to the main bucket would mean we can use it as the dependency for Ant, Gradle, Grails, Groovy, Scala etc. The only downside I can think of is that there might be some confusion as people update.

@martinlindhe maybe give it a few days and if no one raises objections I'd be happy to accept your PRs.

**Comment by martinlindhe** [comment]
Okay, sounds great

**Comment by scottwillmoore** [comment]
That is fine by me, it's probably what most people would prefer.

**Comment by saildata** [comment]
@lukesampson Honestly, I jumped in to lend a hand on this ticket because I had the time that day to answer. I don't develop or (use if I can help it) Java, so I say :+1: :shipit: and keep up the great work! 

I've said it before and I still tell friends at work that *when* I boot Windows I can't work without Scoop. I guess now one could argue that the WSL tom foolery is a piece of Linux in Windows, but I haven't had a chance to mess with it. From what I understand it's not a first class citizen, so projects like Scoop are still vital to getting quick access to many developer tools on a Windows machine.
