### ISSUE TITLE
Git 2.x Not Working

### ISSUE THREAD

**Issue by alvin-nt** [lukesampson/scoop#663]
I tried to upgrade to Git 2.x (was using `git` at version 1.9). However, after `git` was upgraded, the `git` commands related to remote (e.g. `git push`, `git clone`) do not work.

Steps to reproduce:
1. `scoop update git`
2. Set the envvar, as mentioned in the post-installation notes. Also tried to set the envvars manually, both at system scope and user scope
3. Commands not working. `git` just exits without any prompt or error messages.

Notes:
- When executing `$?`, PowerShell prints `True`.
- Changing `GIT_SSH` envvar to `plink.exe` (ssh from putty) does not work either.
- When I try to execute `git` from `cmd`, it prints out an error related to `SSL_CTX_set_alpn_protos`.
- I tried to uninstall and reinstall `git` and `openssh` both locally and globally (w/ `sudo scoop install -g git`). Still no effect.
- I can confirm that the same thing also affects `git-with-openssh` bucket.

I am using Windows 10 64-bit.

Possibly related issue: #638

**Comment by lukesampson** [comment]
Yeah I haven't been able to get the latest git working with SSH either. I stuck with the `git19` install until recently because it did work, and then I just abandoned using SSH with Git and switched to HTTPS instead.

We ended up reverting #638 because the new Microsoft OpenSSH seemed a bit flakey, so I don't think that'd be the problem. Maybe check `scoop list openssh` to make sure you're on v5.x instead of v7.x.

Maybe someone else here has ideas about how to fix it. Otherwise `scoop install git19` or switching to HTTPS might be options.

**Comment by alvin-nt** [comment]
I already tried the 5.x OpenSSH, still not working. Besides, I also tried to clone a public HTTPS repo from Github. The clone command is also not working.

As what @lukesampson suggested, currently I'm using `git19`, since I need git for my daily routine.

In the meantime, I suggest to keep this issue open.
