### ISSUE TITLE
Running `scoop which` throws syntax error

### ISSUE THREAD

**Issue by RobertWHurst** [lukesampson/scoop#673]
I've installed git and openssh on my machine. I tried to run the command `scoop which ssh`, I get the following exception.
```powershell
iex : At line:1 char:59
+ Hurst\AppData\Local\scoop\apps\openssh\5.4p1-1\bin\ssh.exe"
+                                                           ~
The string is missing the terminator: ".
At C:\Users\Robert Hurst\AppData\Local\scoop\apps\scoop\current\libexec\scoop-which.ps1:22 char:28
+         | select -Last 1 | iex
+                            ~~~
    + CategoryInfo          : ParserError: (:) [Invoke-Expression], ParseException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString,Microsoft.PowerShell.Commands.InvokeExpressionCommand
```

**Comment by saildata** [comment]
Hi @RobertWHurst , that's an odd problem - I use the command all the time to find program locations. Looking at the log, the .ps1 file hasn't changed since August, 2015.
Can you provide your PowerShell / Windows version? ` $PSVersionTable.PSVersion`
Windows version? 
Are there any other errors on the stack trace or is this it? 
If you try the command by itself, does it return `ERROR: <command> missing
usage: scoop which <command>` ?
Hopefully this helps narrow down the problem ... good luck!

**Comment by rivy** [comment]
It's a bug in `scoop-which.ps1` uncovered because @RobertWHurst has a space in his username (and therefore his home and scoop paths). The bugged code splits on a space regardless of quoting.
# [see https://github.com/lukesampson/scoop/blob/master/libexec/scoop-which.ps1#L21)

**Comment by saildata** [comment]
@rivy That makes sense. Thanks for the link and for following up. 
I'm not on a Windows machine right now - off the top of my head, isn't there a '-parent' we could use as the target in place of the split string? I think there is also a '-fullname' or something to that effect. If not, forgive my laziness for not waiting until I boot up W8 to confirm.
