### ISSUE TITLE
".exe" shim doesn't set '$env:HOME'

### ISSUE THREAD

**Issue by rivy** [lukesampson/scoop#687]
'$env:HOME' is not tested/created by the ".exe" shim code, which is inconsistent with the "CMD/BAT" and "PS1" shim code. This can result in a missing '$env:HOME' variable for compiled unix-y tools (which generally expect a reasonable '$env:HOME' to function correctly).

For consistency, code to test/create '$env:HOME' should be added to the `shim.exe` code. But, I think a better solution would be to move the whole thing into `install_app()` as I've done on my fork (see b7c8fbf7881a1fd78e5925b15c0075126615c3af). This simplifies the "CMD/BAT" and "PS1" shims considerably, leaving just the essential shim code, and it consolidates the code manipulating '$env:HOME' into one place, testing/creating '$env:HOME' for any installation.

Let me know if you're interested in either type of fix and I can create a PR.

**Comment by lukesampson** [comment]
I'm not sure about the utility of setting `%HOME%` any more. That functionality was [added 3 years ago](https://github.com/lukesampson/scoop/commit/f3d4d2cf0b395a20080ac49d9b9eabcf079c4a06), but I can't find a case where it's actually useful or necessary.

In case it does end up being necessary for some apps, I have added an `env_ensure_home` directive for manifests to set %HOME% at the install point, rather than in shims. It's similar to your implementation, but conditionally activated by a manifest. That code path is commented out though and scheduled for deletion if I can't justify keeping it there.

If time passes and we don't see any errors, I'll declare this cruft and get rid of it. Closing this issue for now.
