### ISSUE TITLE
Suggestion for Additional Support

### ISSUE THREAD

**Issue by imsiddharth** [lukesampson/scoop#799]
[ RethinkDB >= 2.2](http://rethinkdb.com/)
    [GraphicsMagick (for resizing screenshots)](https://sourceforge.net/projects/graphicsmagick/files/)
    [ZeroMQ libraries](http://zeromq.org/)
    [Protocol Buffers libraries](https://github.com/google/protobuf)
    [yasm ](http://yasm.tortall.net/)
    [pkg-config](https://www.freedesktop.org/wiki/Software/pkg-config/)

Thanks

**Comment by saildata** [comment]
@imsiddharth Can you clarify what the request is? I think you're asking for additional applications to be added, but that's just guessing from your links. Let everyone know so that it can be resolved. If it is a request to add to the repo, there is great documentation on app manifests in [the wiki](https://github.com/lukesampson/scoop/wiki/App-Manifests).

**Comment by chrjean** [comment]
RethinkDB is already on scoop.sh (https://github.com/lukesampson/scoop/blob/master/bucket/rethinkdb)

**Comment by r15ch13** [comment]
[pkg-config.json](https://github.com/lukesampson/scoop/blob/master/bucket/pkg-config.json) is available.
Are those other tool still relevant? They seem to be outdated.
