### ISSUE TITLE
How to modify local official buckets&manifest

### ISSUE THREAD

**Issue by cygmris** [lukesampson/scoop#881]
I tried to install docker-machine via scoop, but it fails deal to the network circumstance.

I wonder if there is a way by which we can change the url of **official buckets (docker-machine etc)** manifest of my installed scoop. therefore I can download the required file in other place where with good network status to my local network.

with a little explorer, I'v located the versions and extracts buckets at `C:\Users\Administrator\AppData\Local\scoop\buckets`. But how can I locate the official manifest docker-machine manifest ?

**Comment by lukesampson** [comment]
The main bucket is under `~/appdata/local/scoop/apps/scoop/current/bucket` – you can find `docker-machine.json` in there.

If you modify that file in place, you'll run into problems the next time you run `scoop update`, because git will see uncommitted changes.

But if you copy it into a working directory with `cp ~/appdata/local/scoop/apps/scoop/current/bucket/docker-machine.json ./docker-machine.json`, you should be able to modify the `url` inside the manifest to point to your local network and then install it by running `scoop install ./docker-machine.json`.
